### ISSUE TITLE
Non-functional Buttons on Pack Details Screen in Native Application

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1039]
**Describe the bug**
Buttons on the Pack Details screen are not functioning when tapped.

**To Reproduce**
1. Launch the Application
2. Log in to your account
3. Navigate to the menu and tap on 'Packs'
4. Tap on any pack to view its details
5. Attempt to interact with the buttons on the Pack Details screen

**Expected behavior**
All buttons on the Pack Details screen should respond to taps and perform their designated actions

**Screenshots**

https://github.com/andrew-bierman/PackRat/assets/166146993/a259bc9d-5ce6-433c-b661-a179054331a1

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 
 - Browser: chrome, safari
 - Version; 14.5

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 18
 - Browser: Chrome, Safari

**Comment by Isthisanmol** [comment]
Hi @JewelTee, please check  #1041.
