### ISSUE TITLE
UI Breaks When Updating Profile Preferences in Native App

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#1049]
**Describe the bug**
Upon attempting to update the user unit preference from LB to KG, the user profile changed to null.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/20aef16c-11a9-48f4-9aff-139531cdf92a)
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/8432e681-3a32-465b-9c8f-0a73082e5e5d)

When attempting to recreate the bug by switching the unit preference from KG to LB, the app became unresponsive and stuck on this screen.                                 
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/90d087c5-0b82-4c54-b78e-bda1b405d2b3)

**To Reproduce**
1. Go to Profile
2. Click on Settings.          
3. Update the Preferred Units by selecting a different weight unit.
4. Click on "Update Profile" to apply the changes.

**Expected behavior**
Ensure that the unit preference chosen by the user is consistently applied to all pack and trip details throughout the app without causing crashes.

**Comment by JewelTee** [comment]
> **Describe the bug** Upon attempting to update the user unit preference from LB to KG, the user profile changed to null. ![image](https://private-user-images.githubusercontent.com/122357250/344363327-20aef16c-11a9-48f4-9aff-139531cdf92a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTIzMDgsIm5iZiI6MTcxOTgxMjAwOCwicGF0aCI6Ii8xMjIzNTcyNTAvMzQ0MzYzMzI3LTIwYWVmMTZjLTExYTktNDhmNC05YWZmLTEzOTUzMWNkZjkyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNTMzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGY2ZDBkYTQ3MmRiNDFhMWQ5ODkxZjA3YTU0MjVjMWRhNWU5YmU2OGQ5ZDVmNTY5NjY4MTdmY2U5OWMwODg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gVBmVf2behVEvq_S0K7qSzSW08vtHxQUgW0pMFqmm7Q) ![image](https://private-user-images.githubusercontent.com/122357250/344363211-8432e681-3a32-465b-9c8f-0a73082e5e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTIzMDgsIm5iZiI6MTcxOTgxMjAwOCwicGF0aCI6Ii8xMjIzNTcyNTAvMzQ0MzYzMjExLTg0MzJlNjgxLTNhMzItNDY1Yi05YzhmLTBhNzMwODJlNWU1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNTMzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTExOWExMTM2YTljMDVkMWI5MTljNTI4YWI3NzY0NDg1M2VmNDYzZGViNjEyZjQzYjc2M2NiYWU0MTcwNTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c2HWhi50b5LOXJAP0BNoQ-vVaxV8lVpudAzq872oC0s)
> 
> When attempting to recreate the bug by switching the unit preference from KG to LB, the app became unresponsive and stuck on this screen. ![image](https://private-user-images.githubusercontent.com/122357250/344363512-90d087c5-0b82-4c54-b78e-bda1b405d2b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MTIzMDgsIm5iZiI6MTcxOTgxMjAwOCwicGF0aCI6Ii8xMjIzNTcyNTAvMzQ0MzYzNTEyLTkwZDA4N2M1LTBiODItNGM1NC1iNzhlLWJkYTFiNDA1ZDJiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwMVQwNTMzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZWM3ZDlmMzBiNDFhMGNkMmJiNWNiZTgxNDk1OTY2YWE0NjY4OWExNDAzOTkyYjM5YTkyYjZkNGNlMGE5MzcwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pYZ2g_NYkxCsN8FvqFDQD1J_262vfti4BDHuoANjP-w)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to Profile
> 2. Click on Settings.
> 3. Update the Preferred Units by selecting a different weight unit.
> 4. Click on "Update Profile" to apply the changes.
> 
> **Expected behavior** Ensure that the unit preference chosen by the user is consistently applied to all pack and trip details throughout the app without causing crashes.

@pinocchio-life-like - this issue is also occuring when you change other settings on the users profile (Changing profile picture, changing username, changing name etc.)

**Comment by EngrAJ8888** [comment]
Hi @pinocchio-life-like ,  just following up on this. Could you please provide us with an update? Thanks!


cc: @JewelTee

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 https://github.com/andrew-bierman/PackRat/pull/1062
