### ISSUE TITLE
Search Feature in Pack Not Working

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#1054]
**Describe the bug**
While attempting to add new items globally to the pack, I observed that the search function displays only recently added items, even when I haven't typed anything specific related to those items. It appears to be limited to showing only the first 5 items created.

**To Reproduce**
1. Go to Packs
2. Click on any saved packs
3. Add items from global

**Expected behavior**
Search function should work accurately, with all items from global being searchable and able be added to the user's own pack.

**Screenshots**
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/f5ef46b3-0bfa-424a-96e9-443c2bc4746f)

**Additional context**
This issue is visible in native app and web.

**Comment by Tadjaur** [comment]
working on it.

**Comment by EngrAJ8888** [comment]
Confirmed that updates are working - closing this ticket.
