### ISSUE TITLE
Fix Activity Text in Trip Details

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#1055]
**Describe the bug**
I created a trekking trip, but when I viewed it, only the activity was saved under 'Trips'. This option appears to be the only one available for other trips as well. The trip details such as description, destination, and date are showing correctly.

**To Reproduce**
1. Navigate to Trips.
2. Click on "Create Trip."
3. Search for destinations and fill out the remaining fields.
4. Scroll down to the Activity section and choose "Trekking."
5. Save the Trip.

**Expected behavior**
The trip details should accurately display the activity chosen by the user.

**Screenshots**
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/06a459b6-0b6f-41a0-aa02-11829fbc579c)

**Additional context**
This issue is visible in native app and web.

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 check this please: https://github.com/andrew-bierman/PackRat/pull/1065
