### ISSUE TITLE
Chat Feature Not Appearing on Android Mobile App

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1073]
**Describe the bug**
The chat feature does not appear on the Android mobile app, making it impossible for users to access and use the chat functionality.

**To Reproduce**
1. Open the mobile app on the device
2. Navigate to the section where the chat feature should be accessible.
3. Observe that the chat feature is missing or not visible.

**Expected behavior**
The chat feature should be visible and accessible to users within the app.

**Comment by pinocchio-life-like** [comment]
@JewelTee check the latest andrew_testing please, thanks!

**Comment by JewelTee** [comment]
@pinocchio-life-like I cannot check it on the latest andrew_testing branch, the mobile app is crashing.

**Comment by Isthisanmol** [comment]
@JewelTee please check " Fix chat icon visibility on native #1102 "
