### ISSUE TITLE
Native app fixes/improvements 

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1075]
### Content Labeling

- [x] #1088
![Screenshot_from_2024-07-05_10-42-16](https://github.com/andrew-bierman/PackRat/assets/166146993/dab5630d-d375-40ef-a88d-6072284ed2d5)

- [x] This item may not have a label readable by screen readers
![Screenshot_from_2024-07-05_10-42-23](https://github.com/andrew-bierman/PackRat/assets/166146993/b1ae08c7-27ac-4e97-8b9c-2852811d2c74)
![64311cdc-8c2c-4855-847f-0207ea527dbe](https://github.com/andrew-bierman/PackRat/assets/166146993/e2c0da22-698c-426c-a408-e9c8eadd7c27)

- [x] Multiple clickable items share this location on the screen
![Screenshot_from_2024-07-05_10-44-04](https://github.com/andrew-bierman/PackRat/assets/166146993/869de785-35ac-41d9-bc42-145c089f5ecd)

- [x] Multiple items have the same description
![Screenshot_from_2024-07-05_10-41-23](https://github.com/andrew-bierman/PackRat/assets/166146993/5126fab8-d14d-47f7-9bc3-449136f0c332)

![Screenshot_from_2024-07-05_10-41-34](https://github.com/andrew-bierman/PackRat/assets/166146993/214914de-68f5-48f2-8a17-6bc75ed3422f)

### Touch Target Size

- [x] Consider making this clickable item larger (Consider making the height to 48 dp or larger)
![Screenshot_from_2024-07-05_10-43-18](https://github.com/andrew-bierman/PackRat/assets/166146993/dac16884-4523-47e3-85db-1b20f6154c6a)
![Screenshot_from_2024-07-05_10-43-30](https://github.com/andrew-bierman/PackRat/assets/166146993/203e5b09-98d1-4b58-b9f3-bf8d61ea4f70)
![Screenshot_from_2024-07-05_10-43-39](https://github.com/andrew-bierman/PackRat/assets/166146993/35931a2d-f6b7-4367-84af-c20f6d26b223)
![Screenshot_from_2024-07-05_10-43-45](https://github.com/andrew-bierman/PackRat/assets/166146993/bbc5b42b-06c1-46f8-82cd-9d51076c592a)

### Low Contrast

- [x] Consider increasing this item's text foreground to background contrast ratio ( Consider increasing this item's text contrast ratio to 3.00 or greater )
![Screenshot_from_2024-07-05_10-44-17](https://github.com/andrew-bierman/PackRat/assets/166146993/2fc463ea-8fce-488c-8f89-c6ad38288e2d)
![Screenshot_from_2024-07-05_10-44-27](https://github.com/andrew-bierman/PackRat/assets/166146993/00997df7-4113-4015-b19f-f801b44c3fdc)
![Screenshot_from_2024-07-05_10-44-34](https://github.com/andrew-bierman/PackRat/assets/166146993/055bac3a-b176-49aa-afd4-379a9ece44f5)
![Screenshot_from_2024-07-05_10-44-39](https://github.com/andrew-bierman/PackRat/assets/166146993/0a58c053-a02b-4a34-92a3-a73178870d29)

### Android compatibility issues

- [x] Double Splash Screen
![Screenshot_from_2024-07-06_08-36-07](https://github.com/andrew-bierman/PackRat/assets/166146993/0a310da8-ede8-4942-99fc-c024ad2e8c1a)

**Comment by Isthisanmol** [comment]
@JewelTee please check " Fix content label issues on native #1105 " for content labelling issues.

**Comment by Isthisanmol** [comment]
@JewelTee  please check " Fix double splash screen #1110 "  for double splash screen.
