### ISSUE TITLE
Refreshing Page After Pack Deletion Leads to Sign in Page

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1086]
**Describe the bug**
After deleting a pack and refreshing the page, users are unexpectedly redirected to the sign-in page.

**To Reproduce**
1. Go to 'https://packrat.world/' / 'https://packrat.pages.dev/'
2. Sign in to your account
3. Navigate to the menu and click on 'Packs'
4. Click on any pack and delete the pack
5. Refresh the page 
6. Observe that the user is redirected to the sign-in page.

**Expected behavior**
The user should remain on the current page

**Screenshots**

https://github.com/andrew-bierman/PackRat/assets/166146993/8a934034-cce8-4872-897c-a94608f6dd76

**Comment by taronaleksanian** [comment]
@JewelTee @Isthisanmol 
this issue was fixed on this PR
https://github.com/andrew-bierman/PackRat/pull/1092
