### ISSUE TITLE
Profile Functionality Issue in Native App

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#1103]
**Describe the bug**
The profile option in the native app isn't working correctly, the app crashes whenever you try to navigate to the Profile section.

**Screenshots/ Recording**
https://github.com/user-attachments/assets/32de4559-d0bd-4061-8351-c3874bf76dbb

**Additional context**
This works on the web, but we're experiencing issues within the native app.

**Comment by taronaleksanian** [comment]
Hi @EngrAJ8888 fixed it here
https://github.com/andrew-bierman/PackRat/pull/1108/files
