### ISSUE TITLE
Improve the Layout of the Sorting Option in Native App

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#1104]
**Describe the bug**
Update the sorting option to display at the bottom of the screen instead of the top for the trips, packs, and feed screens.

**Screenshots**
![image](https://github.com/user-attachments/assets/48f91eef-dcbe-4923-963c-d0629ab9ad82)
![image](https://github.com/user-attachments/assets/0a5a93a0-b30f-46ac-b92c-69804a5cd065)

**Additional context**
This issue is only in native app.

**Comment by EngrAJ8888** [comment]
Additionally, please update text to ensure "Sort By" on the Items Screen is visible. Please see photo below for reference.
![image](https://github.com/user-attachments/assets/82752999-e255-43e4-b15e-1a874b309866)

**Comment by Isthisanmol** [comment]
@EngrAJ8888 please check " Enhance dropdown #1112 "

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, the sorting option is still located at the top of the screen instead of the bottom for both the feed and pack screens. Please refer to the attached photo for reference. Thank you! 
![image](https://github.com/user-attachments/assets/e4329a66-a428-4fae-a929-0b5e49cb8104)

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol, the sorting option is still located at the top of the screen instead of the bottom for both the feed and pack screens. Please refer to the attached photo for reference. Thank you! ![image](https://private-user-images.githubusercontent.com/122357250/350659045-e4329a66-a428-4fae-a929-0b5e49cb8104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mjc5MjMsIm5iZiI6MTcyMTYyNzYyMywicGF0aCI6Ii8xMjIzNTcyNTAvMzUwNjU5MDQ1LWU0MzI5YTY2LWE0MjgtNGZhZS1hOTI5LTBiNWU0OWNiODEwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMlQwNTUzNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjVkZjEyZDFhYWE0ZTlhMmMyZTdjYTE0YjhhMmJlOTc2ODFiZGI0MDBiM2ZkYTY0YmY5OTcwMGU4OGY1ODY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.95-eKl8-ndSeKh8Pt1pbcDDNCpa7w2gcM6pFKly__DU)

It was at the bottom when I last fixed it. But I'll check again and fix it.

**Comment by Isthisanmol** [comment]
@EngrAJ8888, please check " Dropdown layout fix #1126 "
