### ISSUE TITLE
Profile Screen UI Broken on Native

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1109]
**Describe the bug**
- [x] The UI of the Profile Screen is broken

![Screenshot_2024-07-18-14-02-13-08_248012cd4184c9416d967f4c08ee0567](https://github.com/user-attachments/assets/f1115966-f2b3-4223-833b-f08d07ebd8e9)

![Screenshot_2024-07-18-14-02-25-18_248012cd4184c9416d967f4c08ee0567](https://github.com/user-attachments/assets/3623db39-3ddc-4f8d-97db-02d7bd3e7d40)

**Comment by Tadjaur** [comment]
On it.

**Comment by Tadjaur** [comment]
@JewelTee the second screenshot ( edit profile ) is fixed.
I'm not able to reproduce the issue on the first screen.

**Comment by JewelTee** [comment]
> @JewelTee the second screenshot ( edit profile ) is fixed. I'm not able to reproduce the issue on the first screen.

Okay sure! 
Just Go to the "feed" screen and tap on the ❤ below the 'favorite' text 
here is a screen recording for reference :)

https://github.com/user-attachments/assets/fc1d8b0b-4afc-438c-b80d-1bc4d7dabc61

**Comment by Tadjaur** [comment]
I see.
For some reason, the feed screen creation has been disabled.

**Comment by JewelTee** [comment]
> I see. I don't have feed on local db, and for some reasons, the screen to create feed has been disabled.

oh okay. you mentioned the second one is already fixed ( edit profile ), do you have a pr for that fix?

**Comment by Tadjaur** [comment]
Oh no, I wanted first to see how I can reproduce the first case before creating a pr with both of them.
But you are right I will first create a pr for the second one.
I'm Doing that.

**Comment by JewelTee** [comment]
@Tadjaur oh okay. Thank You!

**Comment by taronaleksanian** [comment]
> I see. I don't have feed on local db, and for some reasons, the screen to create feed has been disabled.

Hi @Tadjaur don't you see feed screen on your local?

**Comment by Tadjaur** [comment]
@taronaleksanian The feed screen is empty.

**Comment by taronaleksanian** [comment]
@Tadjaur what do you mean "create a feed". In feed you see packs created by both the current user and other users packs. So you can add a public pack using another user.

**Comment by Tadjaur** [comment]
Wow, sorry :man_facepalming: I'm talking about the trip.

When I go on the feed screen I have a message `No Public Feed Data Available`.
I created two public pack, but the feed screen is still empty.
I try to create the trip, but the screen (to create trip) is empty.

**Comment by Tadjaur** [comment]
@taronaleksanian to avoid making assumptions, I would like to know what I need to do to see data on the feed screen ?

**Comment by taronaleksanian** [comment]
okay please use production api URL for now @Tadjaur
