### ISSUE TITLE
Downloaded Maps not displaying the map previews

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1111]
- The "Downloaded Maps" section in the mobile view is not displaying the map previews correctly. The map tiles are blank.
                      
![348949249-a94ebbfd-3215-4851-8c15-8f0fb79ea4dc](https://github.com/user-attachments/assets/e02e5ca6-9403-4249-8694-2f685f24cf26)

**Comment by Tadjaur** [comment]
@JewelTee this has been fixed at #1114

**Comment by Tadjaur** [comment]
@Isthisanmol I hope you haven't started the task yet, I needed to fix this quickly to finalize issues #1069 and make sure everything is working properly and my update hasn't broken anything else.

**Comment by Isthisanmol** [comment]
> @Isthisanmol I hope you haven't started the task yet, I needed to fix this quickly to finalize issues #1069 and make sure everything is working properly and my update hasn't broken anything else.

I had not started that.Thanks!
