### ISSUE TITLE
Validation workspace is not hot reloading when we make changes

### ISSUE THREAD

**Issue by Tadjaur** [andrew-bierman/PackRat#1132]
**Describe the bug**
When we make any change on the validation workspace, we need to remove node_modules from the root and reinstall the packages

**Expected behavior**
The validation workspace should hot reload when the make any change on the workspace.

**Comment by andrew-bierman** [comment]
One short term solution is to run 'yarn postinstall' FYI I think that usually rebuilds the modules

**Comment by andrew-bierman** [comment]
I'm pretty sure this is an issue with our root tsconfig - I think if we add the packages in here we will get hot reload back? i know this is a frustrating bug

**Comment by Tadjaur** [comment]
> I'm pretty sure this is an issue with our root tsconfig - I think if we add the packages in here we will get hot reload back? i know this is a frustrating bug

I will try that. Since this task do not have a hight priority, I plan to look and fix the failure of playwright tests first.

**Comment by Tadjaur** [comment]
> I'm pretty sure this is an issue with our root tsconfig - I think if we add the packages in here we will get hot reload back? i know this is a frustrating bug
@andrew-bierman unfortunetely it didn't work. it look like each platform have is own way to handle this.

I create a PR that fix this issue #1139 on native application and server application.
