### ISSUE TITLE
Fix playwright tests

### ISSUE THREAD

**Issue by Tadjaur** [andrew-bierman/PackRat#1133]
**Describe the bug**
The playwright test is failing on any PR run.

**Expected behavior**
All playwright tests must pass.

**Screenshots**
![image](https://github.com/user-attachments/assets/b7dd5da4-3b14-4601-8a49-321b708ade06)

**Comment by andrew-bierman** [comment]
One thing we could do here is pull the preview URL from the CF github bot and run the tests on there

**Comment by andrew-bierman** [comment]
FYI @JewelTee fixed a few of these so now we have a couple passing, still a lot timing out. They are failing to access the nav menu on web i believe

**Comment by JewelTee** [comment]
@Tadjaur closing this ticket now, issue was fixed in #1155
