### ISSUE TITLE
System Allows Password Update With Incorrect 'Old Password'

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1167]
**Describe the bug**
When attempting to change the password, the system allows the change even when an incorrect password is entered in the 'old password' field. This is a security flaw, as it should validate the current password before permitting any changes.

**To Reproduce**
1. Navigate to the account settings page.
2. Select the option to change the password.
3. Enter an incorrect current password in the 'old password' field.
4. Enter a new password in the 'new password' and 'confirm password' fields.
5. Click on the 'Change Password' button

**Expected behavior**
The system should display an error message indicating that the 'old password' is incorrect and prevent the password change.

**Additional context**
This issue occurs both on the web and on native

**Comment by Isthisanmol** [comment]
Hi @JewelTee , please check " Add verification for oldPassword #1191 ". I think it resolves the issue.
