### ISSUE TITLE
Visibility Issue for Text Elements in Light Mode

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1172]
**Describe the bug**

- Some texts are not visible in Light mode on the Destination Query Page.

Please see the images below for light mode and dark mode comparison. Thank you!

**Screenshots**
![b7369491-6125-4c54-bbc0-2a2b3b2bcbc9](https://github.com/user-attachments/assets/756deda2-347b-48c4-8872-a6f8258d75ee)
![2afc1fe5-e17c-4b72-a908-fa1bbde91931](https://github.com/user-attachments/assets/7620e1dd-fa0e-4f30-9747-d7db27b9c420)

**Comment by EngrAJ8888** [comment]
Also including this one - 

- Remove the '0' from the 'View All Feed' button as shown below
<img width="1096" alt="image" src="https://github.com/user-attachments/assets/5c7c4b8f-a041-4c47-9a9d-5d901a5c7b21">

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol - I've noticed that the Privacy Policy page text isn't visible also in light mode. Please refer to the photo below.
<img width="360" alt="Screenshot 2024-08-21 at 5 11 35 PM" src="https://github.com/user-attachments/assets/23842d3d-4f14-4885-b69f-a4d2d936c972">

-It is visible in dark mode
<img width="360" alt="Screenshot 2024-08-21 at 5 13 08 PM" src="https://github.com/user-attachments/assets/24505cef-1f6d-4367-a471-2345a146a9a5">

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, please check " Take text color from theme #1178 " for last two items.

**Comment by Isthisanmol** [comment]
Hi @JewelTee, you can also check the #1178 pr for first item.I have fixed that.

**Comment by JewelTee** [comment]
> Hi @JewelTee, you can also check the #1178 pr for first item.I have fixed that.

issue is fixed, thank you!
