### ISSUE TITLE
Native App Issue: Text Not Visible When Typing Destination Query in Search Field 

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1173]
**Describe the bug**

- When typing a destination query into the search field of the native app while in **DARK MODE**, the text is not visible or properly displayed. The whole page is just showing a white background. 
**Screen recording**

https://github.com/user-attachments/assets/a590776a-1d5b-4d22-bb74-8b2760279af7

- The search icon is not visible while in **LIGHT MODE**
**Screenshot**
![454058093_1548115542799222_7820731581628169817_n](https://github.com/user-attachments/assets/df3057c8-0650-49bc-aa05-3b0aa05f2d39)

**Comment by Isthisanmol** [comment]
Hi @JewelTee, please check " Fix native search theme #1175 ".

**Comment by JewelTee** [comment]
@Isthisanmol thanks for fixing this issue.
