### ISSUE TITLE
Update 'Similar Pack' Card Size in Native App

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#1177]
**Describe the bug**
The Similar Pack card is too large and is covering up other details, which forces users to scroll to see more of the pack's details. Can we resize the card so that the whole pack is visible at once?
This issue is visible in Feed and Pack page. 

Also, Andrew mentioned that we should make this a horizontal view and remove the side arrows on native. 

**Screenshots**
<img width="360" alt="Screenshot 2024-08-21 at 5 25 15 PM" src="https://github.com/user-attachments/assets/0433e5b3-dfcf-4445-bfbc-2420821dd070">
<img width="360" alt="Screenshot 2024-08-21 at 5 41 49 PM" src="https://github.com/user-attachments/assets/d75bdd35-e377-41fe-beb5-43e6c03523e1">

<img width="360" alt="Screenshot 2024-08-21 at 5 25 38 PM" src="https://github.com/user-attachments/assets/7d32da23-b473-428e-8946-b624b9b4fad9">

**Comment by andrew-bierman** [comment]
We probably do not need the side arrows on native. A horizontal scroll view would be sufficient there 

On web they make more sense

**Comment by andrew-bierman** [comment]
We revised our card ui a bit, need to show similarity score in the similar card list without breaking the other places these cards are used
