### ISSUE TITLE
Case Sensitivity Issue with Login Credentials

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1179]
**Describe the bug**
The login system currently does not enforce case sensitivity for email addresses. Users can log in with email addresses that differ in capitalization from the correct credentials, which may cause confusion or security issues.

**To Reproduce**

1. Navigate to the login page.
2. Enter the following credentials:
 Email: ZOOT3@email.com
 Password: 12345678
3. Click the "Log In" button.

**Expected behavior**
The system should display an error message indicating 'incorrect email or password' because the email is not entered with the exact capitalization as required.

**Actual Result**
The system successfully logs in the user despite the capitalization difference in the email address.

**Additional context**
Correct Credentials:
Email: zoot3@email.com
Password: 12345678

**Comment by andrew-bierman** [comment]
Email addresses are actually not case sensitive jfyi so this is functioning correctly, assuming it's just for the email field. 

I don't think we have username login either, but if so we then usernames should also be case insensitive

**Comment by JewelTee** [comment]
@andrew-bierman got it. Will close this issue for now
