### ISSUE TITLE
IOS Build UI Issue: Overlapping Elements in the Bottom Navigation Bar

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1189]
**Describe the bug**
The bottom navigation bar on the screen has overlapping elements

**Screenshots**
![456463270_1225433795307666_3679792677604095393_n](https://github.com/user-attachments/assets/7803f048-eba1-4f7d-b0ac-1c1df93345f8)

![454769741_1048373820152045_2517778443115226062_n](https://github.com/user-attachments/assets/537bd7ce-39d7-42dd-9b69-64e28ebc4673)

**Comment by EngrAJ8888** [comment]
- [ ] Add more space above the Destination Search Bar and make the search bar larger. The text appears small on mobile and almost touches the phone’s header. 
![IMG_5220](https://github.com/user-attachments/assets/d5760d82-6fc2-4ea1-973c-cfb5f5c0519f)

**Comment by taronaleksanian** [comment]
@JewelTee  profile screen issues were fixed, you can check it out here
https://github.com/andrew-bierman/PackRat/pull/1222
