### ISSUE TITLE
IOS Build UI Issue: Text Visibility on Light Mode and Dark Mode

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1190]
**Describe the bug**

- Some texts are not visible on light mode and dark mode

**Screenshots**

![454836104_526251099923749_2071091064528109981_n](https://github.com/user-attachments/assets/2dca14dc-7f54-4362-98e1-eaccdbd553f3)
![454878717_1547475606179082_5017852231551164747_n](https://github.com/user-attachments/assets/cd3d072a-d78c-430f-8fee-510e7894af9b)

**Comment by EngrAJ8888** [comment]
Adding this one as well - 
 - text visibility issue on the login page when in dark mode
![Dark Theme-2](https://github.com/user-attachments/assets/2a5b1388-c47b-4148-9867-518d89ba583e)

**Comment by Isthisanmol** [comment]
> Adding this one as well -
> 
>     * text visibility issue on the login page when in dark mode
>       ![Dark Theme-2](https://private-user-images.githubusercontent.com/122357250/361188689-2a5b1388-c47b-4148-9867-518d89ba583e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjQ4NTMsIm5iZiI6MTcyNTM2NDU1MywicGF0aCI6Ii8xMjIzNTcyNTAvMzYxMTg4Njg5LTJhNWIxMzg4LWM0N2ItNDE0OC05ODY3LTUxOGQ4OWJhNTgzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QxMTU1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGMxNTBlYzZiZDRiYzkxYWFmOTA1MmY2OWU5OGIzNzY5NjE2NzgwMDIzMTNlODZjMjViNWM3NTExYzQ3NGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wh0gwNfVeEsAeemWcTdAh2EW1cnB4YHL7Z7YqoJmwpA)

This will be fixed once #1214 is merged.
