### ISSUE TITLE
Empty Cards Showing up Under Similar Packs

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1200]
**Describe the bug**
In the "Similar Packs" section some cards are blank and do not show any data. It would be better not to display empty cards. 

**To Reproduce**
1. Navigate to the page or section where similar packs are displayed.
2. Observe the first card, which displays data correctly.
3. Observe the other cards after the first one.

**Expected behavior**
All cards in the "Similar Packs" section should display relevant data with no additional blank cards.

**Screenshots**

**IOS**

https://github.com/user-attachments/assets/83cea727-3e51-46ec-89ea-a99859ad4432

**Android**

https://github.com/user-attachments/assets/d042432d-bd7a-4f66-9c9f-be8252515999

**Additional context**
The issue persists both on IOS and Android.

**Comment by mikib0** [comment]
Did you observe this in the dev environment?

**Comment by JewelTee** [comment]
> Did you observe this in the dev environment?

No, I observe this in the production build

**Comment by andrew-bierman** [comment]
We should probably do no arrows on native and just allow for horizontal scroll. The arrows are good for web I think but make less sense in native, and we can gain some more screen real estate if we remove

**Comment by mikib0** [comment]
I agree. Additionally the corousel doesn't scroll on swipe on native in my experience. Will work this.

**Comment by mikib0** [comment]
Maybe we have a seperate issue to track that or in #1177, but this one is resolved.
