### ISSUE TITLE
Native App: UI Enhancements

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1201]
**UI Enhancements for both IOS and Android Build**

- [x] Add Spacing Between Sections. The current UI on the Pack screen displays item details without adequate spacing between the sections. 

![fffff](https://github.com/user-attachments/assets/e99fb616-d2fd-4113-8327-7ce5c0ebae32)

- [x] The current UI on the Create Pack screen does not effectively use the available screen space. Adjust the layout so that the form elements are centered vertically on the screen, making the interface more balanced (Just like the Login Screen)

![image0](https://github.com/user-attachments/assets/1617848d-a5a4-46ec-a766-5feebc58cd54)

- [x] Align the Search Bar text to the left
![image0](https://github.com/user-attachments/assets/d52543e5-dddd-479c-a221-4847f20066a3)

**Comment by Isthisanmol** [comment]
Hi @JewelTee, please check " Style changes #1206 ".

**Comment by andrew-bierman** [comment]
Feed preview needs horizontal scrolling on native if we take away the buttons jfyi

**Comment by Isthisanmol** [comment]
> Feed preview needs horizontal scrolling on native if we take away the buttons jfyi

Already done that.

**Comment by Isthisanmol** [comment]
@JewelTee @andrew-bierman  Please check  "Horizontal scrolled enabled #1211".
