### ISSUE TITLE
Native Build UI Enhancement

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#1279]
- [x] #1280
![459376294_7158259567632358_5069854596845203586_n](https://github.com/user-attachments/assets/bed31366-2adf-4adf-bf98-a1f4b1e573c1)

- [x]  The cards on the Profile Screen are overlapping
![460054615_1208756187064044_9029655090127304698_n](https://github.com/user-attachments/assets/eb26bc09-e8ab-42a3-9a94-570c6c8e1a73)

- [x]  Overlapping elements
<img width="339" alt="Screenshot 2024-10-02 at 9 38 15 PM" src="https://github.com/user-attachments/assets/53c01efc-9200-48e1-be0b-1fa6a090ce07">

- [x]  Trip Screen broken
![459874903_523572273625378_3200153167925555100_n](https://github.com/user-attachments/assets/47245cca-4053-4e95-bb54-8cef69216be4)

- [x]  Pack details on the Create Trip screen 
![460148068_2867722083401140_2439012633216342697_n](https://github.com/user-attachments/assets/2414fecf-a985-4e1b-8ada-943a0af012bb)

- [x] Make the spaces in between cards the same
<img width="341" alt="Screenshot 2024-10-02 at 9 41 51 PM" src="https://github.com/user-attachments/assets/41488116-7a60-4ef2-b713-37d91d611b51">

**Comment by EngrAJ8888** [comment]
Adding this one as well

- [ ] Adjust margins and padding to remove dead space
<img width="357" alt="image" src="https://github.com/user-attachments/assets/6153454a-bc18-4673-b779-ddc35fdffdd3"><img width="357" alt="Screenshot 2024-10-03 at 6 30 01 PM" src="https://github.com/user-attachments/assets/ef10e55e-0fa6-40d8-b92e-35d91dd7863b">
<img width="357" alt="image" src="https://github.com/user-attachments/assets/815e4070-5450-4090-8f41-9ea8bff6e9da"><img width="357" alt="image" src="https://github.com/user-attachments/assets/e8909f43-79a7-4c16-aa24-c3f02674604e">
<img width="357" alt="Screenshot 2024-10-03 at 6 36 08 PM" src="https://github.com/user-attachments/assets/834899df-cfbd-4b35-977d-56a4791b23c1">



- [ ] Adjust the text margin in the search BAR and increase its size for better visibility. 
<img width="357" alt="image" src="https://github.com/user-attachments/assets/1bc92b1c-1961-42a9-a2dd-4c026796fdf4">

**Comment by JewelTee** [comment]
- [ ] Search icon not visible in light mode

![460175768_404106852527651_7365096631523769699_n](https://github.com/user-attachments/assets/9ba919bb-0ed0-488e-8db3-77f0a545a425)

- [ ] In the destination query screen, the text in the search field is missing in dark mode. 

![460141972_1079183133789472_2538362130603694398_n](https://github.com/user-attachments/assets/18cfec48-a10e-4ecc-a4d7-eba09aa8fda5)
![459415453_1089773835904942_8937599458703516155_n](https://github.com/user-attachments/assets/a3719873-e4d1-466d-95af-e5e3d808dbea)
