### ISSUE TITLE
Breaking Change

### ISSUE THREAD

**Issue by himanshuanand74** [andrew-bierman/PackRat#33]
example:
**tripController.js - GET request should not have body as validations of celebrate do not work on it.**

https://www.npmjs.com/package/celebrate mentions :-
Additional Info
According the the HTTP spec, **GET requests should not include a body in the request payload. For that reason, celebrate does not validate the body on GET requests.**

**Comment by andrew-bierman** [comment]
Thanks for flagging this, please see linked pull request for my suggested fix
