### ISSUE TITLE
test the app for crud operations

### ISSUE THREAD

**Issue by aezazali1997** [andrew-bierman/PackRat#496]

**Comment by aezazali1997** [comment]
### Search does not do anything


![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/533b4883-ebdf-491a-9002-9b07a3c10ea8)



![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/26d24897-de84-4751-8295-6d6097266d62)



![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/a145d55b-e714-4a72-9962-ff55a3bf5b8c)



![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/3ce38f5e-4087-4556-b9f7-49a5ff9a39dc)




![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/81a8815d-248e-486b-a999-3aa11c543577)



![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/eb68a05d-4cd4-45e6-8c1b-84b7db98285f)





![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/9f6efcf2-0dc0-48d9-87c7-88b7124a0ceb)




![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/847b0437-684c-484a-babe-5176170fa77a)




![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/d0ca0275-c3db-4bab-b8a8-16092455bb6d)




![Image](https://github.com/andrew-bierman/PackRat/assets/36494368/3b15757b-f682-47a6-a673-a659dd7a8ed7)

**Comment by andrew-bierman** [comment]
Which branch is this from?

**Comment by aezazali1997** [comment]
andrew_testing.
