### ISSUE TITLE
Frontend - Separate Business Logic from UI

### ISSUE THREAD

**Issue by andrew-bierman** [andrew-bierman/PackRat#529]
Our frontend code has grown to be quite messy. Let's fix this.

Some of this will be fixed with the tamagui PR, which implements a ui package to handle our primitives. 

The next step is to refactor our components and screens folders to remove all business logic, and place that logic within custom hooks. 

Here is a great example of how to do this: https://x.com/_georgemoller/status/1739644203867464091?s=46&t=BIQs8xeH5ZAzltdKl3PARg

Also https://stackoverflow.com/questions/69332889/reactjs-separation-of-ui-and-business-logic

https://javascript.plainenglish.io/use-custom-hook-to-separate-logic-ui-in-react-efbe3b4b423a

### Next Steps
Phases:
- [ ]  Moving current component logic to custom hooks
- [ ]  Improving current component logic, removing unnecessary redux logic in favor of standard use state or jotai - I'm thinking for things like search, weather, createTrip etc. not everything needs to move out of redux immediately.

### State Management Improvements
Known Areas That Need Improvement (WIP)
- [x] Search - does not need to be global, can handle with useState in custom hook i think 
- [x] Weather - does not need to be global, can handle with useState in custom hook i think 
- [ ] Create Trip - does not need to be global, can handle with useState OR Jotai in custom hook i think 

### Components 
<details>
<summary>Click to expand the checklist</summary>

- [x] Avatar.tsx
- [x] ThreeDotsMenu
- [x] footer
- [x] pack_table
- [x] Dropdown.tsx
- [x] TripCard.tsx
- [x] hero
- [x] paginationChooseLimit
- [x] DuplicateIcon
- [x] Water.tsx
- [x] inventory
- [x] password-reset
- [x] EditableText
- [x] card
- [x] item
- [x] progress
- [x] GearList.tsx
- [x] carousel
- [x] itemtable
- [x] select
- [x] InputText
- [x] chat
- [x] landing_page
- [x] skeleton
- [x] ItemRow.tsx
- [x] custombutton
- [x] loading-placeholder
- [x] trip
- [x] Loader.tsx
- [x] dashboard
- [x] logo
- [x] user
- [x] PackOptions
- [x] destination
- [x] map
- [x] weather
- [x] ScoreContainer.tsx
- [x] details
- [x] modal
- [x] SearchInput.tsx
- [x] dialog
- [x] multi_step
- [x] SummaryCard.tsx
- [x] feed
- [x] pack

Note, all of these should be in folders. The files in root of components should be moved to their own folders while we do this. All primitive ui elements should be coming from our packages/ui folder. 

</details>

### Screens 

<details>
<summary>Click to expand the checklist</summary>

- [x] Drawer.tsx
- [x] Navigation.tsx
- [x] about
- [x] dashboard
- [x] header
- [x] #648
- [x] LoginScreen.tsx
- [x] RegisterScreen.tsx
- [x] appearance
- [x] feed
- [x] items
- [x] user

Note, all of these should be in folders. The files in root of components should be moved to their own folders while we do this. All primitive ui elements should be coming from our packages/ui folder.

</details>

Please keep track of components in progress below, so that we do not overlap work.

**Comment by shahzi113awan** [comment]
:Working on Pack

**Comment by andrew-bierman** [comment]
Let's take this in phases like the following:

1. Moving current component logic to custom hooks
2. Improving current component logic, removing unnecessary redux logic in favor of standard use state or jotai - I'm thinking for things like search, weather, createTrip etc. not everything needs to move out of redux immediately.

**Comment by andrew-bierman** [comment]
- [ ]Search input

initial work on search input is done. still need to fix state logic after phase 1, still going through store

**Comment by andrew-bierman** [comment]
Added list of components to issue FYI, let's track what has been done and what is still pending

**Comment by yasTheDreamer** [comment]
> - [x] search input
> 
> initial work on search input is done. still need to fix state logic after phase 1, still going through store 

I'll have to rebase the SearchInput performance PR on this.

Ps: i'm almost done with the feed's VirtualList performance fix with tamagui and tanstack

**Comment by andrew-bierman** [comment]
> > * [x]  search input
> > 
> > initial work on search input is done. still need to fix state logic after phase 1, still going through store
> 
> I'll have to rebase the SearchInput performance PR on this.
> 
> Ps: i'm almost done with the feed's VirtualList performance fix with tamagui and tanstack

yes that would be great to rebase that, thanks. most of your logic should move over to the hook smoothly, i think we just need to update the on change handler and useRef in component side now

**Comment by fshah21** [comment]
Moved about screen logic into another custom hook. https://github.com/andrew-bierman/PackRat/pull/537/files

**Comment by taronaleksanian** [comment]
:Working on Dashboard

**Comment by taronaleksanian** [comment]
Moved dashboard screen logic into custom hooks. https://github.com/andrew-bierman/PackRat/pull/540

**Comment by taronaleksanian** [comment]
:Working on User screen

**Comment by taronaleksanian** [comment]
Moved User screen logic into custom hooks. https://github.com/andrew-bierman/PackRat/pull/541

**Comment by fshah21** [comment]
Moved items screen logic into custom hooks : https://github.com/andrew-bierman/PackRat/pull/542

**Comment by taronaleksanian** [comment]
:Working on Settings screen

**Comment by taronaleksanian** [comment]
Moved Settings screen logic into custom hooks https://github.com/andrew-bierman/PackRat/pull/545

**Comment by taronaleksanian** [comment]
:Working on Login screen

**Comment by taronaleksanian** [comment]
Moved Login screen logic into custom hooks https://github.com/andrew-bierman/PackRat/pull/546

**Comment by taronaleksanian** [comment]
:Working on Register screen

**Comment by shahzi113awan** [comment]
in progress 
components:
 [pack_table,
 Dropdown.tsx,
 TripCard.tsx]

**Comment by taronaleksanian** [comment]
Moved Register screen logic into custom hooks https://github.com/andrew-bierman/PackRat/pull/548
I rebased from https://github.com/andrew-bierman/PackRat/pull/546

**Comment by taronaleksanian** [comment]
:Working on Navigation screen

**Comment by andrew-bierman** [comment]
One thing I noticed as well, we have a couple primitive ui elements still in our /components folder, ie dropdown, modal, etc. that should probably be handled via @packrat/ui (packages/ui). 

The goal is all our base ui components live in the package, and the components in /client are the more complete pieces to go along with the new logic hooks. Component = Primitive ui elements + logic from hooks, essentially.

**Comment by andrew-bierman** [comment]
Additionally, every file in /hooks or /components should be in their own folders ie /components/packs and hooks/packs. Just to make it more scalable going forward as we add more features.

**Comment by taronaleksanian** [comment]
Moved Navigation and Drawer screen logic into custom hooks https://github.com/andrew-bierman/PackRat/pull/550

**Comment by taronaleksanian** [comment]
:Working on Trip screen

**Comment by shewit-gh** [comment]
:wroking on feeds

**Comment by yangTauTauAjah** [comment]
working on "progress" component

**Comment by gauthamdas** [comment]
working on ScoreContainer.tsx

**Comment by taronaleksanian** [comment]
@shahzi113awan I'm working on trip screen, I saw you are working on the Tripcard component, did you finish it?, or if you haven't started yet can I take it?

**Comment by shahzi113awan** [comment]
> @shahzi113awan I'm working on trip screen, I saw you are working on the Tripcard component, did you finish it?, or if you haven't started yet can I take it?
it's done already

**Comment by shahzi113awan** [comment]
@taronaleksanian  can you please mark checked the items which you have done , so we don't need to search through comments

**Comment by taronaleksanian** [comment]
@shahzi113awan have merged it to the "andrew_testing" branch?

**Comment by shahzi113awan** [comment]
not yet

> @shahzi113awan have merged it to the "andrew_testing" branch?

**Comment by taronaleksanian** [comment]
> @taronaleksanian can you please mark checked the items which you have done , so we don't need to search through comments

I do when I merge them to the "andrew_testing" branch

**Comment by taronaleksanian** [comment]
can you kindly provide the branch where that component was done? @shahzi113awan

**Comment by shahzi113awan** [comment]
> can you kindly provide the branch where that component was done? @shahzi113awan
let me push the code

**Comment by shahzi113awan** [comment]
> > can you kindly provide the branch where that component was done? @shahzi113awan
> > let me push the code

[552](https://github.com/andrew-bierman/PackRat/pull/552)

**Comment by shahzi113awan** [comment]
in progress :
 map
 weather

**Comment by taronaleksanian** [comment]
> in progress : map weather

I went through the code and noticed that weather and map are necessary for creating trips so I think I can switch to another tasks, while you are working on them

**Comment by taronaleksanian** [comment]
in progress  components:
modal
dialog

**Comment by gauthamdas** [comment]
working on password-reset

**Comment by gauthamdas** [comment]
working on Water.tsx

**Comment by shahzi113awan** [comment]
in Progress :
 chat

**Comment by yangTauTauAjah** [comment]
need to review pull request for progress component #560

**Comment by uros-simeunovic** [comment]
In progress:
 - Avatar.tsx
 - GearList.tsx

**Comment by yangTauTauAjah** [comment]
Working on several components:
- trip
- hero
- carousel
- itemtable
- destination

**Comment by taronaleksanian** [comment]
Refactor modal / dialog component done https://github.com/andrew-bierman/PackRat/pull/564

**Comment by taronaleksanian** [comment]
working on
custombutton
multistep

**Comment by taronaleksanian** [comment]
Refactor custom button done https://github.com/andrew-bierman/PackRat/pull/567

**Comment by taronaleksanian** [comment]
Refactor multistep form done https://github.com/andrew-bierman/PackRat/pull/568

**Comment by shewit-gh** [comment]
:working on
Components 

- [ ] footer
- [ ] Pagination choose option 
- [ ] Pack options 
Screen

- [ ] items

**Comment by taronaleksanian** [comment]
working on
skeleton
InputText
EditableText

**Comment by taronaleksanian** [comment]
Refactor skeleton component done https://github.com/andrew-bierman/PackRat/pull/582

**Comment by yangTauTauAjah** [comment]
refactor components:
- DuplicateIcon
- Item
- PaginationChooseLimit

**Comment by yangTauTauAjah** [comment]
refactor components done:
- DuplicateIcon
- Item
- PaginationChooseLimit

#594

**Comment by taronaleksanian** [comment]
refactor components done

card
EditableText
loading-placeholder
ThreeDotsMenu

https://github.com/andrew-bierman/PackRat/pull/602

**Comment by taronaleksanian** [comment]
refactor InputText done

https://github.com/andrew-bierman/PackRat/pull/604

**Comment by taronaleksanian** [comment]
working on

logo
landing_page

**Comment by taronaleksanian** [comment]
refactor landing_page logo done

landing_page https://github.com/andrew-bierman/PackRat/pull/615
logo https://github.com/andrew-bierman/PackRat/pull/616

**Comment by pinocchio-life-like** [comment]
I've made progress on this issue. Here's what I've done so far: [Inside Screens -> Appearance Folder]

1. Refactored the `AppearanceContainer` component to separate concerns into smaller components.
2. Created new components: `ThemeSwitch`, `DemoCard`, `NativeBaseBox`, `PaperCard`, and `KitchenSink`.
3. Updated the `useAppearance` hook to manage the theme state.

I'm currently working on trip components inside screens. I'll continue to update this issue as I make more progress.

Here's the commit with my changes: [commit 3d2f225cbaf829313bcb94978a793d702a84a817]

**Comment by pinocchio-life-like** [comment]
Done Refactoring TripDetailsComponent From inside Trip Folder inside screens:

Here's the commit with my changes: [commit 62b915ec284e25559dbbd170b30d07afff2e75e0]

Please review and if you have suggestions let me know.

**Comment by taronaleksanian** [comment]
moved auth logic from redux to tanstack-query
https://github.com/andrew-bierman/PackRat/pull/649

**Comment by taronaleksanian** [comment]
working on 
move search state from redux to tanstack-query

**Comment by pinocchio-life-like** [comment]
Done refactoring about page. Separated the Created a new component and imported into index.js and took out the style on page to different file and imported into index.js.

Also I noticed some error with my last commit and did some update as well.

So, for those working on this issue please review and update accordingly.
