### ISSUE TITLE
Bug - RNMapbox Integration Broken

### ISSUE THREAD

**Issue by andrew-bierman** [andrew-bierman/PackRat#58]
**Describe the bug**
Our rnmapbox integration is completely broken on native iOS and Android. This was working in the past, but I believe a recent change may have broken it. We should go back through the set up process based on the library docs and see if we did something wrong.

**To Reproduce**
1. Go to andrew_testing branch, and run the simulator on iOS or Android. Navigate to the create a trip page.
iOS - map component is either empty or the entire page does not load. 

Android - on my end, builds fail with this error:

```
"FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':rnmapbox_maps:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':rnmapbox_maps:debugCompileClasspath'.
   > Could not resolve com.mapbox.maps:android:10.13.0.
     Required by:
         project :rnmapbox_maps
      > Could not resolve com.mapbox.maps:android:10.13.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.13.0/android-10.13.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/maps/android/10.13.0/android-10.13.0.pom'. Received status code 401 from server: Unauthorized
   > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.
     Required by:
         project :rnmapbox_maps
      > Could not resolve com.mapbox.mapboxsdk:mapbox-sdk-turf:6.11.0.
         > Could not get resource 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom'.
            > Could not GET 'https://api.mapbox.com/downloads/v2/releases/maven/com/mapbox/mapboxsdk/mapbox-sdk-turf/6.11.0/mapbox-sdk-turf-6.11.0.pom'. Received status code 401 from server: Unauthorized"
```

**Expected behavior**
We should see our map preview from the maps/NativeMap.native.js file. 

**Screenshots**

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 14 
 - OS:  iOS 16.2

**Comment by andrew-bierman** [comment]
What I have tried since this post:

- Downgrading react-native version to 0.71.4
- Upgrading rnmapbox to version 10.0.7-rc.1
- Simplifying NativeMap component to just a simple mapview. 
- Generating new key from mapbox, again with full permissions. 
- Going back through the docs to evaluate if we missed a step, it seems we covered everything. 

Still having errors on my end.

**Comment by W1MMER** [comment]
Follow this guide: https://stackoverflow.com/a/67247291/9377254
