### ISSUE TITLE
@rnmapbox/maps native code not available. Make sure you have linked the library and rebuild your app

### ISSUE THREAD

**Issue by imrizwan** [andrew-bierman/PackRat#637]
**Describe the bug**
@rnmapbox/maps native code not available. Make sure you have linked the library and rebuild your app is showing on landing page (might break application later)

**To Reproduce**
1. Go to 'Landing Page' / Just after first page of application

**Expected behavior**
Uncaught Error should not appear as it can break application later

**Screenshots**
<img width="388" alt="image" src="https://github.com/andrew-bierman/PackRat/assets/17934962/bb948d8a-d073-4474-b528-a24a4dd147ca">

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max
 - OS: iOS 17.0
 - 
**Additional context**
@rnmapbox/maps native code not available. Make sure you have linked the library and rebuild your app

**Comment by kudzilenett** [comment]
how did you solve this
