### ISSUE TITLE
search page

### ISSUE THREAD

**Issue by Haysam-Bin-Tahir** [andrew-bierman/PackRat#707]

**Comment by andrew-bierman** [comment]
Some additional comments:

- [ ] This is a native only screen at the moment. I think it would be good to have search bar in the header (similar to search on github mobile app)
- [ ] We should not show the same dropdown we show on web, instead we should have a virtualizedlist of proper search rows that fill whole screen. same as searching repo's on github mobile app. 
- [ ] if possible, it would be cool to somehow implement the dashboard search to redirect to the search page for native, as it will be much better ux than the dropdown we currently have which is more web feeling

**Comment by barathiofficial** [comment]
I am working on this issue
