### ISSUE TITLE
Alerts that Reflect Standards: Ensure the use of the Alert component aligns with expected standards, with appropriate titles, messages, and button configurations. See tamagui Alert with native set to true.

### ISSUE THREAD

**Issue by andrew-bierman** [andrew-bierman/PackRat#713]

**Comment by taronaleksanian** [comment]
@andrew-bierman  Can you please provide more details or some resources on this, do we need to use this instead of toast components on native?

**Comment by andrew-bierman** [comment]
Dropping this link for reference, it was nearly complete but there was a rendering issue on a screen 

https://github.com/andrew-bierman/PackRat/pull/746

**Comment by andrew-bierman** [comment]
We do need tamagui toasts but this specific issue was about alerts for deleting confirmation. If you go to alert dialog on tamagui docs you will see. We only would use in a few spots right now

**Comment by andrew-bierman** [comment]
@mikeCyb this could be good one

Toasts using tamagui + burnt to replace our current implementation.

**Comment by mikeCyb** [comment]
@andrew-bierman Got it
