### ISSUE TITLE
Feeds screen crash on android (expo app)

### ISSUE THREAD

**Issue by taronaleksanian** [andrew-bierman/PackRat#763]
**Describe the bug**
When I move to feed screen, app crashes

**To Reproduce**
1. move to expo directory and run with tunnel "npx expo start --tunnel"
2. Go to 'Feed' screen by clicking on its item in the bottom menu 
3. You'll see, that app crashes

**Expected behavior**
It shouldn't happen

**Screenshots**
![Screenshot_2024-03-18-23-14-53-770_host exp exponent](https://github.com/andrew-bierman/PackRat/assets/62029107/be789b24-10f4-4392-9784-d2082992b049)

**Comment by Tadjaur** [comment]
@taronaleksanian I this one has been fixed, can you confirm?

**Comment by taronaleksanian** [comment]
@Tadjaur I don't face the issue on my Android phone, thanks, @JewelTee @EngrAJ8888 can you make sure there are no issues if you have a chance, thanks

**Comment by JewelTee** [comment]
@Tadjaur @taronaleksanian I don't face this issue also. I tested the android app with the latest update 👍🏻

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian and @Tadjaur, I didn't encounter this issue during my testing with the app. Thank you!
