### ISSUE TITLE
Add Field Descriptions to 'Register Account' Option & Resolve New Account Signup Issue 

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#765]
**Describe the bug**
When setting up an account, users are required to fill out specific fields with their information. However, the fields lack clear guidance on what information is needed for each field. And The signup option fails to register an account.

**To Reproduce**
1. Visit URL - https://packrat.world/
2. Click on the the upper right menu
3. Select Register
4. Fill out fields with the correct information
    Name
    Email address
    Username
     Password
5. Click “Sign up”

**Expected behavior**
Clear field descriptions should be visible during the registration process and successful registration prompt with email verification request.

**Screenshots**

![2](https://github.com/andrew-bierman/PackRat/assets/122357250/789e44fd-ba60-462c-b50c-7aea44130a40)

**Additional context**
Browser: 
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

Smartphone 
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by EngrAJ8888** [comment]
Validated test fields are now visible.
Still can't register using email
![16](https://github.com/andrew-bierman/PackRat/assets/122357250/52d00f76-47c9-4225-99d0-0c9f0d6ed1a9)

**Comment by Tadjaur** [comment]
I tested on the `andrew_testing` branch, I was able to register but I didn't get an email verification request.

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur, I attempted to register a dummy email address, but there was no confirmation or notification indicating that the registration was successful. When I tried to log in using the account credentials I had just created, I was unable to log in.

![23](https://github.com/andrew-bierman/PackRat/assets/122357250/ab5bbe5e-0229-4eb2-bec2-4eaac4f4b2c7)

I use this preview link as well - https://packrat-dev-qj5h.onrender.com

**Comment by EngrAJ8888** [comment]
Field Descriptions to 'Register Account' is already resolved.

There are still issues in the Account Signup

**Comment by taronaleksanian** [comment]
@EngrAJ8888 I tried in the latest development version of our app locally and it worked. can you kindly say which URL are you using where you see issues?

**Comment by EngrAJ8888** [comment]
@taronaleksanian - I'm using this live version link 
https://packrat-dev-qj5h.onrender.com

**Comment by Tadjaur** [comment]
Oh @EngrAJ8888 Sorry, I didn't take over the task because it was already assigned to @taronaleksanian.

**Comment by EngrAJ8888** [comment]
@Tadjaur Oh sorry about that, I tagged the wrong person.

**Comment by Tadjaur** [comment]
@taronaleksanian can you share progress with @EngrAJ8888? 
If you don't have the bandwidth to complete the task, please share the progress and assign the task to me.

**Comment by jeweltee** [comment]
I encountered the same issue, I cannot register a new account. I used this link - https://packrat-dev-qj5h.onrender.com/

**Comment by EngrAJ8888** [comment]
Checked using the new testing link: 
https://16a3e7be.packrat.pages.dev
https://packrat.pages.dev

This is issue is now resolved. Closing task.
