### ISSUE TITLE
Issue: Unable to Add Items to Pack 

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#766]
**Describe the bug**
Adding items to a pack does not function properly. Items fail to save after a brief loading period.

**To Reproduce**
1. Visit the URL: https://packrat.world
   same issue here: https://packrat-dev-qj5h.onrender.com
3. Log in to your account with the following credentials:
4. Email: zoot3@email.com
5. Password: 12345678
6. Navigate to the main page.
7. Click on the "Create a pack" option, under quick actions.
8. Provide a name and set public visibility to No.
9. Select “Add Item”.
10. Enter the following:
    Item Name: Chips
    Weight: 0.1
    Quantity: 2
    Category: Food
14. Click on “Add Item”

**Expected behavior**
Added items should be saved within the pack.

**Screenshots**

![3](https://github.com/andrew-bierman/PackRat/assets/122357250/de10d34e-db2c-448d-8266-1883c92b84b2)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by andrew-bierman** [comment]
This issue occurs on native side as well. Likely new frontend validation or data missing from handle submit call.

**Comment by MuhammadHassan03** [comment]
This issue is also solved in this PR : https://github.com/andrew-bierman/PackRat/pull/777

**Comment by EngrAJ8888** [comment]
I validated this fix
Thank you! closing this one out.
