### ISSUE TITLE
Pack Search and Sorting Malfunction, Copy-Paste Feature Missing

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#768]
**Describe the bug**
The search and sorting features for packs aren't functioning correctly at the moment. Also, you can't paste copied items into other packs.

**To Reproduce**
1. Visit the URL: https://packrat.world
   same issue here: https://packrat-dev-qj5h.onrender.com
3. Log in to your account with the following credentials:
4. Email: zoot3@email.com
5. Password: 12345678
6. Navigate to the main page and select “Pack”.
7. Utilize the search engine to locate a saved pack.
8. Attempt to use the sort option
9. Open “Testing AJ” pack.
10. Select Copy
11. Navigate back to menu option and select any saved packs

**Expected behavior**
- Search and sort options should operate seamlessly.
- Users should be able to copy items from one pack and paste them into another.

**Screenshots**

![5](https://github.com/andrew-bierman/PackRat/assets/122357250/67a7d1be-8c8c-42f3-b7b1-b33c36e5746f)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by Tadjaur** [comment]
> Users should be able to copy items from one pack and paste them into another.

@EngrAJ8888 The copy option only seems to add the pack link to the clipboard, so you can share or paste it wherever you want.

Does your comment means the current behavior is not expected and we need to instead copy all items of the current pack and paste them into another?

**Comment by shahzi113awan** [comment]
@Tadjaur  i'm currently working on this issue

**Comment by shahzi113awan** [comment]
Sorting and search functionality is fixed

**Comment by shahzi113awan** [comment]
> > Users should be able to copy items from one pack and paste them into another.
> 
> @EngrAJ8888 The copy option only seems to add the pack link to the clipboard, so you can share or paste it wherever you want.
> 
> Does your comment means the current behavior is not expected and we need to instead copy all items of the current pack and paste them into another?

@EngrAJ8888 ?
please clear this

**Comment by shahzi113awan** [comment]
@EngrAJ8888 , @andrew-bierman  
- There is not any paste button while adding 
details of pack
- There is not any save button in detail form if we have pasted items ,
-Should the items append in previous ones or just override the existing ones

**Comment by andrew-bierman** [comment]
> @EngrAJ8888 , @andrew-bierman
> 
> * There is not any paste button while adding
>   details of pack
> * There is not any save button in detail form if we have pasted items ,
> * Should the items append in previous ones or just override the existing ones

I believe there is some confusion around the button for copying the link to the pack for basic sharing, and the feature that copies a pack. 

When actually copying a pack, you would create a new pack with the same items. 

Currently there is no pasting functionality, we can add global items into an existing pack. Or copy and entire pack and modify our cloned version. 

does that make sense?

**Comment by EngrAJ8888** [comment]
Hi @shahzi113awan, I've checked using the preview link of the PR: #796
I've noticed that only four items can be added from the global item list. Could you please include this in the update? Please refer to the photo below for clarification.
Please refer to the photo below.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/938f9cbd-3f89-478f-9187-07f965f72668)

**Comment by EngrAJ8888** [comment]
@shahzi113awan, bumping this one up. Thank you!

**Comment by EngrAJ8888** [comment]
Hi @shahzi113awan, could you please provide an update? Below are the pending items that still need to be addressed:

- [ ] Implement the option to copy the entire pack of other users and allowing them to modify the cloned pack.
- [ ] When searching for global items to add to the pack, only the four most recently added items are currently showing.

I'm using this link for testing: https://app-release.packrat.pages.dev

Thanks!

**Comment by EngrAJ8888** [comment]
The pending items on this ticket are being addressed in another ticket. We'll proceed to close this one out. Thanks!
