### ISSUE TITLE
Issue: Unable to Toggle Theme

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#770]
**Describe the bug**
Clicking the toggle switch for night mode fails to activate the desired theme change.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com/
2. Log in to your account with the following credentials:
3. Email: zoot3@email.com
    Password: 12345678
    Navigate to the main page.
6. Click on the "Appearance" option, 
7. Attempt to change the theme by toggling the switch.

**Expected behavior**
Users should be able to switch between light mode and dark mode by clicking the toggle switch.

**Screenshots**
![8](https://github.com/andrew-bierman/PackRat/assets/122357250/8f413c6a-ca9c-4643-9e18-80a8f1343bee)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by pinocchio-life-like** [comment]
Resolved in PR: https://github.com/andrew-bierman/PackRat/pull/781

**Comment by EngrAJ8888** [comment]
Validated updates. closing task
