### ISSUE TITLE
Unable to Access "Create a Trip" Option

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#771]
**Describe the bug**
When users try to create a trip, they're met with an error message saying, "Application error: a client-side exception has occurred," which prevents from accessing the trip creation page.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Navigate to the main page.
6. Choose the “Create a trip” option from the quick action menu
7. And also choose ‘Trips” from the menu option
8. Select “Create”

**Expected behavior**
Users should be able to access the page for creating a trip seamlessly without encountering any errors.

**Screenshots**
![10](https://github.com/andrew-bierman/PackRat/assets/122357250/eecb8d02-b11a-4aa5-ba53-59b552aa0d75)

**Desktop (please complete the following information):**
Browser: 
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by pinocchio-life-like** [comment]
Resolved in https://github.com/andrew-bierman/PackRat/pull/781

**Comment by pinocchio-life-like** [comment]
Also fixes: https://github.com/andrew-bierman/PackRat/issues/767

**Comment by EngrAJ8888** [comment]
Validated updates, closing task
