### ISSUE TITLE
Saved Items Not Displaying in Items Feed

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#774]
**Describe the bug**
Users are unable to view saved items in the Items feed and cannot add new items. The page displays no options or details.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com/
2. Log in to your account with the following credentials:
3. Email: zoot3@email.com
4. Password: 12345678
5. Navigate to the main page.
6. Click on the “Items”

**Expected behavior**
Users should be able to view their saved global items and have the option to add new items.

**Screenshots**
![13](https://github.com/andrew-bierman/PackRat/assets/122357250/5999fa25-f4c8-4097-8d5f-87aecf8df08f)

**Desktop (please complete the following information):**
Browser: 
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by pinocchio-life-like** [comment]
Resolved in PR: https://github.com/andrew-bierman/PackRat/pull/781 @EngrAJ8888

**Comment by EngrAJ8888** [comment]
Validated updates in test branch - closing task. Thank you!
