### ISSUE TITLE
Category Functionality and Total Weight Calculation Issue when Adding Items to Pack

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#783]
**Describe the bug**
Upon adding items to a pack, users encounter a malfunction in the category functionality and total weight calculation. Despite specifying categories such as food, water, and essentials, the saved categories display as blank for all added items. Additionally, the total weight of the items fails to accumulate correctly.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com/
2. Log in to your account with the following credentials:
   Email: zoot3@email.com
   Password: 12345678
5. Navigate to the main page.
6. Choose the “Create a pack” option from the quick action menu
7. Provide a name and set public visibility to No.
8. Select “Add Items”.
9. Entered the following:
    Item Name: Food
    Weight: 1.5 LB
    Quantity: 3
    Category: Food
14. Click on “Add Item”

**Expected behavior**
Users should be able to accurately categorize items added to their packs. Additionally, the platform should correctly display the total weight of all items added to the pack.

**Screenshots**
![18](https://github.com/andrew-bierman/PackRat/assets/122357250/75289b27-93d6-4fbe-914f-5bd2a43945c7)
![19](https://github.com/andrew-bierman/PackRat/assets/122357250/f14ff92c-6b95-4eee-abf1-dbdd3dcb62f7)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by EngrAJ8888** [comment]
I'd also like to mention that when adding an item, I encountered a limitation—I wasn't able to edit it afterward. Once an item is added, there doesn't seem to be an option to modify.

https://github.com/andrew-bierman/PackRat/assets/122357250/ed14aa3d-d012-448c-b5db-d606125c1de5

**Comment by Isthisanmol** [comment]
PR #797 [https://github.com/andrew-bierman/PackRat/pull/797#issue-2217118112]
resolves the issue on native
