### ISSUE TITLE
Unable to Delete Saved Packs

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#784]
**Describe the bug**
I encounter difficulty when attempting to delete packs I have created, as the delete action does not execute successfully.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com/
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Navigate to the main page.
6. Click on the “Pack” in the main menu.
7. Look for “Test1” and open
8. Select the menu option and delete

**Expected behavior**
Users should be able to delete packs from their account.

**Screenshots**
![20](https://github.com/andrew-bierman/PackRat/assets/122357250/ecbb520c-193e-4948-8bd3-e98ed327cb96)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by Tadjaur** [comment]
In progress!

**Comment by pinocchio-life-like** [comment]
Resolved in: https://github.com/andrew-bierman/PackRat/pull/788 @EngrAJ8888

**Comment by pinocchio-life-like** [comment]
Sorry @Tadjaur, I was just going through, and didn't notice

**Comment by Tadjaur** [comment]
No worries!
