### ISSUE TITLE
Unable to Save Created Trips

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#785]
**Describe the bug**
While using the main dashboard, I encountered an issue where I couldn't save a trip despite using the save function. After creating the trip, I navigated to the trips section but couldn't find the one I had just created.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com/
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Navigate to the main page.
6. Click on the "Create a trip" option, under quick actions.
7. Search for a destination.
8. Select a saved pack from the gear list dropdown.
9. Pick a date range for the trip, click save trip once done
10. Add Trip name and description. 
11. Choose visibility and Click Save

**Expected behavior**
Users should be able to view the trip they created either in the trips menu option or in the feed when the trip is shared publicly.

**Screenshots**
![21](https://github.com/andrew-bierman/PackRat/assets/122357250/f01ff5ef-81fa-4179-9aa0-0d3a951f8912)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by Haysam-Bin-Tahir** [comment]
Sure, I'll take another look.
Also, it'd be helpful if you could share what issues did you face. Were these the same as you mentioned before in this issue?
@EngrAJ8888

**Comment by EngrAJ8888** [comment]
Hi @Haysam-Bin-Tahir 
Thank you for your assistance! Unfortunately, I'm still encountering issues with saving the trips I create.

**Comment by jeweltee** [comment]
I experienced the same bug

**Comment by EngrAJ8888** [comment]
Hi @Haysam-Bin-Tahir , I am using this preview link : https://packrat-dev-qj5h.onrender.com.

**Comment by EngrAJ8888** [comment]
Hi @Haysam-Bin-Tahir  - bumping this one up. Could you please provide an update? thank you!

**Comment by jeweltee** [comment]
@Haysam-Bin-Tahir just want to follow up on this issues. Thanks!

**Comment by jeweltee** [comment]
@Haysam-Bin-Tahir just want to follow up on this issues. Thanks! 

also, the "Save Trip" button is missing 
![Screenshot 2024-04-19 at 12 39 18](https://github.com/andrew-bierman/PackRat/assets/166146993/6fe57116-8252-4d99-88db-216439ffb178)

**Comment by EngrAJ8888** [comment]
Issue is now fixed. Closing this one out.
