### ISSUE TITLE
User Experience with Slider for Viewing Saved Trips and Packs on Web Desktop Profiles

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#786]
**Describe the bug**
Currently, when users visit their own profiles using desktop, there is no slider available to browse through their saved trips and packs. This enhancement suggests the addition of a slider functionality to enable users to view their saved content more conveniently.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Navigate to the main page.
6. Click on “Profile”

**Expected behavior**
Users should find a slider interface upon accessing their profile, allowing them to easily browse through all their saved trips and packs. 

**Screenshots**
![22](https://github.com/andrew-bierman/PackRat/assets/122357250/958523da-338d-411f-94ac-8b37a49850e1)

**Desktop (please complete the following information):**
Browser: 
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Additional context**
The slider feature is currently absent in the test branch but is available in the main branch.
Ensure proper integration of the slider feature from the main branch to the test branch to enable testing and verification.

**Comment by andrew-bierman** [comment]
We should likely make this more of a preview of last 3-5 most recent packs / trips, with a 'See All' button that opens a modal on web, bottom sheet on native with search so its easy for them to find what they are looking for.

**Comment by EngrAJ8888** [comment]
Validated updates. closing this task.
