### ISSUE TITLE
Resolve Search Functionality and Finalize Chat Feature Implementation

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#800]
**Describe the bug**
Upon utilizing the search button, I noticed that it did not trigger any action. Additionally, the chat feature remains incomplete and requires further development.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com/
2. Log in to your account with the following credentials:
   Email: zoot3@email.com
   Password: 12345678
5. Navigate to the main page.
6. Click on the "Create pack" option, under quick actions.
7. Utilize the “Chat” button
8. Navigate to Feeds, Pack and Trips option from the menu
9. Search for name of packs or trips

**Expected behavior**
- Users should be able to use the search button to locate their saved packs, saved trips, and those available globally.
- The chat feature should allow users to ask questions, with a chatbot providing answers to commonly asked queries regarding a specific pack or trip.

**Screenshots**
![26](https://github.com/andrew-bierman/PackRat/assets/122357250/2334aa1c-31c1-4821-b3ea-cb8509d2edb3)

![27](https://github.com/andrew-bierman/PackRat/assets/122357250/da585301-a741-4ebf-9676-2641de9903d9)

![28](https://github.com/andrew-bierman/PackRat/assets/122357250/aa313bab-287b-4543-88ec-d5575665b2d8)

**Desktop (please complete the following information):**
Browser: 
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs 17.4.1
 - Browser: safari
 - Version: 17.4.1

**Comment by pinocchio-life-like** [comment]
Check This PR: https://github.com/andrew-bierman/PackRat/pull/804 and let me know if issues or updates

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 I have fixed the issue also has some minor implementation changes from last time. check and let me know. Thanks!

**Comment by EngrAJ8888** [comment]
Hi @pinocchio-life-like - thanks for the update! the search functionality in the feed menu is now working.

However, it seems like there's an issue with the chat functionality. Thank you! 
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/efd495d7-92df-441e-af63-17492a55e0dd)

**Comment by EngrAJ8888** [comment]
Hi @pinocchio-life-like , just wanted to bring this to your attention again. Thanks!

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888  Got it will send a new PR soon.

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 Wait I see some issues, sorry!
will let you know after I test all.

**Comment by EngrAJ8888** [comment]
@pinocchio-life-like, got it! just let me know if this is ready for testing. Thank you!

adding in @jeweltee too

**Comment by EngrAJ8888** [comment]
I've reviewed the PR link, and the chat feature has already been fixed. Closing this task now.
