### ISSUE TITLE
UI Update Issues on Mobile Web

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#801]
**Describe the bug**
While testing the web app using mobile, I observed that certain views appear oversized for my screen, restricting horizontal navigation. Additionally, some text on the page gets cut off, impacting the overall usability.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Navigate to the main page.
6. Click on the "Create pack" option, under quick actions.
7. Add items
8. View Profile and and choose settings
9. Choose Items from the Menu option

**Expected behavior**
Users should experience improved usability while accessing the web version on mobile devices.
Please see photo for reference

**Screenshots**

![IMG_0694](https://github.com/andrew-bierman/PackRat/assets/122357250/8c858667-63f4-4051-aa65-3ed6af41d366)
![IMG_0695](https://github.com/andrew-bierman/PackRat/assets/122357250/5e2ed47f-3d15-4d3c-a2c1-51039799ee34)
![IMG_0693](https://github.com/andrew-bierman/PackRat/assets/122357250/5d758400-eaf5-420a-b443-b31e5fde19fe)
![IMG_0696](https://github.com/andrew-bierman/PackRat/assets/122357250/0e9309d3-ccef-4fbe-b715-3a7c47fc8fd1)

**Smartphone (please complete the following information):**
Smartphone 
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by Tadjaur** [comment]
working on it!

**Comment by EngrAJ8888** [comment]
hey @Tadjaur, just bumping this up. Let me know if you have any questions. Thanks you!

**Comment by Tadjaur** [comment]
No questions yet please, On going my plan Is to have PRs tonight.

**Comment by Tadjaur** [comment]
@EngrAJ8888 Since This issue was fixed on #817, I think we can close it!

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur, updates looks good.
Closing this task, thank you!
