### ISSUE TITLE
Unauthorized Editing of Other Users' Packs in Global

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#806]
**Describe the bug**
Users are able to edit packs belonging to other users in the Global section, which should not be permitted. Users should not have the option to modify or delete items in packs created by other users.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com
2. Log in to your account with the following credentials:
    Email: Email52@email.com
    Password: 12345678
5. Navigate to the main page.
6. Click on the "Create pack" option under quick actions.
7. Choose "Yes" for the "Is Public" option.
8. Add Items on the pack.
9. Click on the menu - Choose Logout.
10. Log in to your account with the following credentials:
   Email: zoot3@email.com
   Password: 12345678
13. Navigate to the menu and go to “Feed”.
14. Search for the pack created using the other account.
15. Click on the pack and attempt to edit or delete items.

**Expected behavior**
Users should only be able to view packs or trips created by other users. The capability to copy and paste items is currently being addressed: #768

**Screenshots**
![29](https://github.com/andrew-bierman/PackRat/assets/122357250/bec5b825-6679-4946-a284-47eb8e38721a)

**Desktop (please complete the following information):**
Browser: 
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by taronaleksanian** [comment]
@EngrAJ8888 fixed this issue here https://github.com/andrew-bierman/PackRat/pull/811
please check

**Comment by EngrAJ8888** [comment]
@taronaleksanian Thank you!
This has been merged into the andrew testing branch. Closing this task now.
