### ISSUE TITLE
Password Update Functionality Not Working

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#807]
**Describe the bug**
I tried to change the password, but it didn't work. When I logged back in, the password was still the same.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Navigate to the menu and go to “Profile”.
6. Click on the “Settings” icon
7. Try to add a new password and click on “Change Password”.
8. Click on the menu - Choose Logout.
9. Log in using the same email credentials with the newly set password.

**Expected behavior**
Users should have the ability to update their account password.

**Screenshots**
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/4e95d657-2688-4c8b-bcbf-3a5552f3eb6b)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by taronaleksanian** [comment]
@EngrAJ8888 fixed this issue here please check
https://github.com/andrew-bierman/PackRat/pull/810/files

**Comment by jeweltee** [comment]
I experienced the same bug

**Comment by taronaleksanian** [comment]
@jeweltee where are you testing, can you please provide more information?

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian - I'm still having issues updating user passwords. I'm using this preview link:  https://packrat-dev-qj5h.onrender.com

![image](https://github.com/andrew-bierman/PackRat/assets/122357250/cd7d20d6-2fa3-478d-9926-8e9c162726a7)

**Comment by jeweltee** [comment]
@taronaleksanian Here is a reference of the issue I encountered 
![Uploading screenshot-1712578965617.png…]()

**Comment by jeweltee** [comment]
this issue is now fixed in the new Cloudflare link -https://app-release.packrat.pages.dev/

**Comment by EngrAJ8888** [comment]
Verified on my end as well. Closing task.
