### ISSUE TITLE
Viewing Another User's Saved Trips Shows Own Saved Trips

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#827]
**Describe the bug**
When accessing other users' profiles and viewing their saved trips, the displayed trips belong to the logged-in user instead of the selected profile.

**To Reproduce**
1. Visit the URL: https://packrat-dev-qj5h.onrender.com
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Navigate to the menu and go to “Feed”.
6. Choose any saved packs/trips of other users.
7. Click “View User” to access the selected user's profile.
8. Navigate to the “Your trips” section.
9. Observe the displayed trips on the user profile.

**Expected behavior**
When viewing other users' profiles, only their public saved packs and trips should be visible, not those belonging to the logged-in user.

**Screenshots**
![31](https://github.com/andrew-bierman/PackRat/assets/122357250/11d0b3c8-6cca-48c9-9c93-82d6722d03c5)
![32](https://github.com/andrew-bierman/PackRat/assets/122357250/5e02eb7d-98ee-42d6-928e-b22ab1677da0)

Video reference:
https://github.com/andrew-bierman/PackRat/assets/122357250/610a2ab8-e03a-40c8-be03-69406cab0268

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Smartphone (please complete the following information):**
- Device: iPhone15
 - OS: iOs17.4
 - Browser: safari
 - Version: 17.4

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur 
I noticed that due to the recent update on the Andrew testing branch, the 'view other profile' option is now missing the pack and trips of the user. Would you mind taking a look at this when you have some time? Thank you! 

- [ ] There is No Pack/Trips/Favorites on other users' profile. 
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/5f491b64-e871-4bc4-98d9-cebf4c1262a5)

**Comment by Tadjaur** [comment]
> Hi @Tadjaur 
> I noticed that due to the recent update on the Andrew testing branch, the 'view other profile' option is now missing the pack and trips of the user. Would you mind taking a look at this when you have some time? Thank you! 
> 
> - [ ] There is No Pack/Trips/Favorites on other users' profile. 
> ![image](https://github.com/andrew-bierman/PackRat/assets/122357250/5f491b64-e871-4bc4-98d9-cebf4c1262a5)

Hi @EngrAJ8888 I Will look take à look tokay

**Comment by Tadjaur** [comment]
@EngrAJ8888  which link are you using?

**Comment by Tadjaur** [comment]
@EngrAJ8888 I checked on my side and it's a database problem.
We are now using cloudflare with sqlite for testing and to have the data again we must either import data from mongo db or create new data. (new users for tests, new packs, new trips etc.)

**Comment by Tadjaur** [comment]
> @jeweltee I checked on my side and it's a database problem. We are now using cloudflare with sqlite for testing and to have the data again we must either import data from mongo db or create new data. (new users for tests, new packs, new trips etc.)

@andrew-bierman Please correct me if I'm wrong on this.

**Comment by jeweltee** [comment]
@Tadjaur I just checked it on my end, it seems to be working just fine. When checking the user profile of others, their data is displayed 
![screenshot-1713358575690](https://github.com/andrew-bierman/PackRat/assets/166146993/8f9ee46f-4263-47b8-b6fa-d124ec5e6ff4)

**Comment by EngrAJ8888** [comment]
@Tadjaur  just wanted to let you know that the issue we found during testing is fixed now. Thanks for your help with this. I'll close out the task.
