### ISSUE TITLE
Unable to add Items on Global List 

### ISSUE THREAD

**Issue by jeweltee** [andrew-bierman/PackRat#836]
**Describe the bug**
Unable to add items on Global List 

**To Reproduce**
1. Go to https://packrat.pages.dev/
2.  Log in to your account 
email: zoot3@email.com
password:12345678
3. Navigate to "Menu" and click "Items"

**Expected behavior**
Users should be able to add and see items on the global list 

**Screenshots**
![screenshot-1713016802676](https://github.com/andrew-bierman/PackRat/assets/166146993/45e462ae-0b51-49df-96c7-ddf577e7c773)

**Desktop (please complete the following information):**
 - Windows 11
 - Microsoft Edge
 - Version 22H2

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
  - OS: iOs 17.4
 - Browser : safari
 - Version : 17.4

**Comment by taronaleksanian** [comment]
Hi @jeweltee, thanks for reporting issues.
 I saw those issues, I'm working on them now, we'll have a version with most of the bugs fixed today or tomorrow evening, I'll let you know, so you can test them
