### ISSUE TITLE
Dark Mode Issue: Text Visibility Update Needed

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#839]
**Describe the bug**
When using dark mode, certain text elements are currently not visible.

**To Reproduce**
1. Visit the URL: https://app-release.packrat.pages.dev/
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
5. Search for a destination
6. Create or open existing packs
7. Navigate to the menu and go to “Profile”

**Expected behavior**
Users should be able to clearly view all text elements while using dark mode.

**Screenshots**
![38](https://github.com/andrew-bierman/PackRat/assets/122357250/a66bc0b7-c952-4568-8ce3-d447162eb0e1)
![37](https://github.com/andrew-bierman/PackRat/assets/122357250/2d3baec5-f901-4e02-a625-c367403624b9)
![39](https://github.com/andrew-bierman/PackRat/assets/122357250/ba800d86-83f3-4744-b7f0-77bbcaa838cd)

**Desktop (please complete the following information):**
- Windows 11
 - Microsoft Edge
 - Version: 122.0.2365.92

**Comment by pinocchio-life-like** [comment]
@EngrAJ8888 PR: https://github.com/andrew-bierman/PackRat/pull/867 let me know of issues please, Thanks!
