### ISSUE TITLE
Design Enhancement: Improving User Interface

### ISSUE THREAD

**Issue by jeweltee** [andrew-bierman/PackRat#840]
- [x] Some Texts are not visible to Read
  Global Checklist
 ![screenshot-1713165231394](https://github.com/andrew-bierman/PackRat/assets/166146993/4e5ac847-b58c-44ab-a14d-318bca2aa382)

Preview Link Used - https://app-release.packrat.pages.dev/

**Comment by EngrAJ8888** [comment]
- [ ]  Fix issue where weight text is not displayed when sorting by "most items" and "fewest items 
- [ ] Enhance packs preview to display the number of items alongside their total weights.

![image](https://github.com/andrew-bierman/PackRat/assets/122357250/7ec67acc-7e4e-4f14-97d7-aa46ff691eb1)
