### ISSUE TITLE
Addressing Existing System Issues/Bad UI and Prioritizing Fixes

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#841]
- [x] The 'Next page' button on the global items page is not working. Users can view additional items beyond the first page only by selecting a value greater than 10 from the dropdown menu below.
- [x] Remove edit/ delete column in global items
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/18cc9309-d913-41f6-b2f7-3ea6d023e5b1)

- [x] Fix the alignment of pack details, this issue is visible when viewing other users' packs in the feed.
![40](https://github.com/andrew-bierman/PackRat/assets/122357250/a3b16e74-4183-49ba-b073-e6102ab71a99)

- [x]  Update the search field on the "create a pack" page to be centered.
![41](https://github.com/andrew-bierman/PackRat/assets/122357250/b3b0d8f5-4250-4bfa-b4fe-b90bd9b06cda)

**Comment by jeweltee** [comment]
- [ ] Resize "Add Pack" button (It's too wide) 
![screenshot-1713191216431](https://github.com/andrew-bierman/PackRat/assets/166146993/54d12c67-e00f-4672-a128-bf0693998abb)

**Comment by jeweltee** [comment]
- [ ] search menu dropdown is overlapping on other text field
![screenshot-1713192428408](https://github.com/andrew-bierman/PackRat/assets/166146993/d4333462-716c-4903-9ad6-f90a40c5e168)

**Comment by EngrAJ8888** [comment]
- [ ] In the mobile web version, update the display of the Pack and scoring section.
![42](https://github.com/andrew-bierman/PackRat/assets/122357250/1e8d8358-a824-40ee-a3fd-07f4c37c108f)

**Comment by andrew-bierman** [comment]
Let's make sub issues for these to track

**Comment by EngrAJ8888** [comment]
Hey @andrew-bierman, the ticket has been updated accordingly.

@shahzi113awanm, thank you handling this task. We've added the latest list of required updates to the ticket. If you have any questions or need clarification on anything, don't hesitate to reach out to me or @jeweltee. 

Thank you!

**Comment by shahzi113awan** [comment]
<img width="516" alt="Screenshot 2024-04-18 at 8 29 03 AM" src="https://github.com/andrew-bierman/PackRat/assets/34761350/f0729783-2240-4c5a-a9c3-30694de034a8">

**Comment by shahzi113awan** [comment]
having some zod errors while creating pack 
same was the case in adding  global items that is fixed already ✌️

**Comment by jeweltee** [comment]
> having some zod errors while creating pack same was the case in adding global items that is fixed already ✌️

hi @shahzi113awan creating a pack is working fine on my end. here is a screen record for reference.
I am using this link -https://app-release.packrat.pages.dev/
[d049fb09-5c43-4d45-9056-cb1ff7848bda.webm](https://github.com/andrew-bierman/PackRat/assets/166146993/7b35ea86-9d76-4467-a8e6-03722a97dae6)

**Comment by andrew-bierman** [comment]
- [ ] About page doesn’t scroll on native
- [ ] pack create modal inputs are super narrow
- [ ] Pack details blank on native 
- [ ]

**Comment by jeweltee** [comment]
- [ ] Arrows on the Create Trip Page are not visible in Light mode 
![4ACFD9DD-FD75-4A87-A522-0ED8200A355D](https://github.com/andrew-bierman/PackRat/assets/166146993/20106f32-cf56-412f-9776-5372ba943fa5)

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, Please check PR: #884. I think it closes the  "Pack details blank on native" issue.

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888 , Please check PR: #893. It closes the "About page doesn’t scroll on native" issue.

**Comment by EngrAJ8888** [comment]
Closing this task as it has been completed.
