### ISSUE TITLE
Sign In / Sign Up with Google 

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#842]
**Describe the bug**
Cannot Sign In / Sign Up using Google Account

**To Reproduce**
1. Go to 'https://app-release.packrat.pages.dev/'
2. Navigate to the Menu and Click Log in or Register
3. Click "Sign in with Google"

**Expected behavior**
Users should be able to Register or Sign In using their Google Account

**Screenshots**
![screenshot-1713269333632](https://github.com/andrew-bierman/PackRat/assets/166146993/cce949f5-29ab-43eb-a313-27fd37248aea)
![screenshot-1713190661654](https://github.com/andrew-bierman/PackRat/assets/166146993/8756deda-3bd1-423b-bf0a-dc2fad1a6333)

**Desktop (please complete the following information):**
 - Windows 10 Pro
 - Browser : Microsoft Edge
 - Version : 22H2

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: 17.4
 - Browser : Chrome
 - Version 17.4

**Comment by andrew-bierman** [comment]
@pinocchio-life-like dm me I can give access to gcp

**Comment by pinocchio-life-like** [comment]
@jeweltee  https://github.com/andrew-bierman/PackRat/pull/860 has been approved, but I think env variable for google id hasn't been updated for the previews I believe.

**Comment by pinocchio-life-like** [comment]
@JewelTee I am closing this issue since, it is working on the production build.
