### ISSUE TITLE
Mobile Web Issues 

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#843]
- [x] Search item field not available on mobile web 
![438083196_1594507341324824_2494821132267699606_n](https://github.com/andrew-bierman/PackRat/assets/166146993/f6c5a17a-b482-4645-94af-682e0f8c0d3e)

- [x] Appearance and Logout option missing on mobile web
![438060632_408687995128921_4542354910636225110_n](https://github.com/andrew-bierman/PackRat/assets/166146993/7bd54de2-2b0b-4f94-aa70-8b31acab4662)

**Comment by EngrAJ8888** [comment]
Adding the following issues on this ticket:

In the mobile web version

- [ ] Users are unable to mark packs as favorites directly from the feed page, as the heart button is missing. Currently, this action can only be performed using the web version on a PC. 
![43](https://github.com/andrew-bierman/PackRat/assets/122357250/6254322a-780c-4b02-b01c-bfa173e1fca8)

- [ ] Update the display and alignment of text in the Pack and scoring section. 
![42](https://github.com/andrew-bierman/PackRat/assets/122357250/1e8d8358-a824-40ee-a3fd-07f4c37c108f)

**Comment by Isthisanmol** [comment]
> * [ ]  Search item field not available on mobile web
>       ![438083196_1594507341324824_2494821132267699606_n](https://private-user-images.githubusercontent.com/166146993/322871097-f6c5a17a-b482-4645-94af-682e0f8c0d3e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDY1MzgsIm5iZiI6MTcxODEwNjIzOCwicGF0aCI6Ii8xNjYxNDY5OTMvMzIyODcxMDk3LWY2YzVhMTdhLWI0ODItNDY0NS05NGFmLTY4MmUwZjhjMGQzZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMTQzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZGMxNDJmNDBlZTU3ZjZmOTU2MmUyYTQxNjhlOTlkMWNlNzkzZWJiNThlMjA0OWM0ZTQ0NTc3ZmM3ODY5YmY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZgawHXN_l2-_AuW8cS6zb_jlSqQqfxHng0jdRyL0BhI)
> 
>     * [ ]  Appearance and Logout option missing on mobile web
>       ![438060632_408687995128921_4542354910636225110_n](https://private-user-images.githubusercontent.com/166146993/322872782-7bd54de2-2b0b-4f94-aa70-8b31acab4662.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDY1MzgsIm5iZiI6MTcxODEwNjIzOCwicGF0aCI6Ii8xNjYxNDY5OTMvMzIyODcyNzgyLTdiZDU0ZGUyLTJiMGItNGY5NC1hYTcwLThiMzFhY2FiNDY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMTQzNThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWQzYTYyODAwZmM1MWQ3NmMyNzczMmI1MzI3Y2Q0NDI0NDc4MjhjYzE4ODM5NjA2MDM1YjUwYTY0YjQ0MDNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qrRWz9MCTPU8GxcJuCtqQ__fDWKhTpnJ994EvjZErUQ)

Please check #991 for second item.

**Comment by Isthisanmol** [comment]
@JewelTee Please check #992 for the first item.

**Comment by Isthisanmol** [comment]
> Adding the following issues on this ticket:
> 
> In the mobile web version
> 
>     * [ ]  Users are unable to mark packs as favorites directly from the feed page, as the heart button is missing. Currently, this action can only be performed using the web version on a PC.
>       ![43](https://private-user-images.githubusercontent.com/122357250/322530066-6254322a-780c-4b02-b01c-bfa173e1fca8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE5NTIsIm5iZiI6MTcxODE4MTY1MiwicGF0aCI6Ii8xMjIzNTcyNTAvMzIyNTMwMDY2LTYyNTQzMjJhLTc4MGMtNGIwMi1iMDFjLWJmYTE3M2UxZmNhOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODQwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDcyOGYyNjY5MWYwOTc0MjgxYThiYjk4ZThiZGZjMWE2MTMxNWVlNjU2YmJjYmIzODM4ZDRjZjFlNzcyMWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ZzAlQ5icFgqrAawAV6HItQmH4e0UrBOlwmdRN5bAZ0)
> 
>     * [x]  Update the display and alignment of text in the Pack and scoring section.
>       ![42](https://private-user-images.githubusercontent.com/122357250/322527797-1e8d8358-a824-40ee-a3fd-07f4c37c108f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE5NTIsIm5iZiI6MTcxODE4MTY1MiwicGF0aCI6Ii8xMjIzNTcyNTAvMzIyNTI3Nzk3LTFlOGQ4MzU4LWE4MjQtNDBlZS1hM2ZkLTA3ZjRjMzdjMTA4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODQwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTY5MjA2OTcwYWYwYzk3ZTVkODEwNjk1YTNhYjkxNDJmMjA0OTg5YWI5MWM3NWM5YWRhYTc3ZWRkYjQxNTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cnii-ijp1J7stTSa-UN-553KfD9hGNWNG3Wg_B07mQc)



> Adding the following issues on this ticket:
> 
> In the mobile web version
> 
>     * [ ]  Users are unable to mark packs as favorites directly from the feed page, as the heart button is missing. Currently, this action can only be performed using the web version on a PC.
>       ![43](https://private-user-images.githubusercontent.com/122357250/322530066-6254322a-780c-4b02-b01c-bfa173e1fca8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE5NTIsIm5iZiI6MTcxODE4MTY1MiwicGF0aCI6Ii8xMjIzNTcyNTAvMzIyNTMwMDY2LTYyNTQzMjJhLTc4MGMtNGIwMi1iMDFjLWJmYTE3M2UxZmNhOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODQwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDcyOGYyNjY5MWYwOTc0MjgxYThiYjk4ZThiZGZjMWE2MTMxNWVlNjU2YmJjYmIzODM4ZDRjZjFlNzcyMWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5ZzAlQ5icFgqrAawAV6HItQmH4e0UrBOlwmdRN5bAZ0)
> 
>     * [x]  Update the display and alignment of text in the Pack and scoring section.
>       ![42](https://private-user-images.githubusercontent.com/122357250/322527797-1e8d8358-a824-40ee-a3fd-07f4c37c108f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODE5NTIsIm5iZiI6MTcxODE4MTY1MiwicGF0aCI6Ii8xMjIzNTcyNTAvMzIyNTI3Nzk3LTFlOGQ4MzU4LWE4MjQtNDBlZS1hM2ZkLTA3ZjRjMzdjMTA4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODQwNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTY5MjA2OTcwYWYwYzk3ZTVkODEwNjk1YTNhYjkxNDJmMjA0OTg5YWI5MWM3NWM5YWRhYTc3ZWRkYjQxNTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cnii-ijp1J7stTSa-UN-553KfD9hGNWNG3Wg_B07mQc)

@JewelTee Please check #998  for the first one.
