### ISSUE TITLE
Fix Pack Creation Functionality Issue

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#844]
**Describe the bug**
- [x] When creating a pack, I used the kg/oz/lb unit for the total weight, but upon checking the saved pack, it is displaying the total weight in "grams" for all packs. The unit is also missing on the pack preview as well.
- [x] The edit button is missing when adding packs. Users should be available to edit items when adding their own packs/saved packs.
- [x] Users are unable to input decimal points in the weight field during pack creation. Decimal numbers should be allowed in this field, excluding the quantity field.

**To Reproduce**
1. Visit the URL: https://app-release.packrat.pages.dev/
2. Log in to your account with the following credentials:
    Email: zoot3@email.com
    Password: 12345678
3. Click on the "Create a pack" option, under quick actions.
4. Begin adding items to your pack and ensure that you select KG as the total weight unit.
5. After completing the pack creation process, navigate to the "Pack" option in the menu to view the saved pack.

**Expected behavior**
- Users should have the flexibility to utilize various units of measurement for the total weight of their pack. 
- Users should be able to edit and delete items within their own packs.

**Screenshots**
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/c40adaab-5008-4447-90e5-075c9f8fd324)

![image](https://github.com/andrew-bierman/PackRat/assets/122357250/a2a84f60-6e3c-41d0-8429-07788129cc17)

**Comment by taronaleksanian** [comment]
Hi @EngrAJ8888, I have a few questions on this issue.

1. Can you please provide more details on the unit issue, it seems it's working, please provide a video recording if possible, thanks
2. Should the user be able to edit items of its pack, that are global items of another user.

**Comment by taronaleksanian** [comment]
@EngrAJ8888 here is the preview URL
https://pk-844-fix-pack-issues.packrat.pages.dev/

**Comment by jeweltee** [comment]
hey @taronaleksanian the issue on inputing decimal point in the weight field is now fixed. Thank You

**Comment by taronaleksanian** [comment]
hey @jeweltee thanks, can you please also answer these questions

1. Can you please provide more details on the unit issue, it seems it's working, please provide a video recording if possible, thanks
2. Should the user be able to edit items of its pack, that are global items of another user.

**Comment by jeweltee** [comment]
> hey @jeweltee thanks, can you please also answer these questions
> 
> 1. Can you please provide more details on the unit issue, it seems it's working, please provide a video recording if possible, thanks
> 2. Should the user be able to edit items of its pack, that are global items of another user.

Sure! I will check this first with AJ and update you

**Comment by EngrAJ8888** [comment]
Hey  @taronaleksanian 
1.  Please see the video below for reference.  I utilise KG as the total weight for the pack, but it seems to only save in 'g'. The unit is also missing when viewing all packs in the Pack menu. 

https://github.com/andrew-bierman/PackRat/assets/122357250/d4640ade-7ecc-4771-8034-ca781ecbe43d

2.  Yes, that is correct. Users should be able to edit global items they've cloned/added to their pack, and any changes from the global items should not affect the items on the user's pack.

**Comment by taronaleksanian** [comment]
@EngrAJ8888 @jeweltee Thanks, I'll fix it

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian , I was testing using this link: https://app-release.packrat.pages.dev and ran into an issue. It seems that adding items to the pack isn't functioning properly anymore. Whenever I click "calculate Pack Score," all the items I've added will disappear. Right now, I can only add items from the global list Here's a snapshot of the error message:
Could you please take a look. Thank you! 

![image](https://github.com/andrew-bierman/PackRat/assets/122357250/07714b5a-5d6f-4270-b519-155f3fb07333)

**Comment by taronaleksanian** [comment]
Hi @EngrAJ8888 thanks for reporting, The URL where you are testing is deprecated, let me show you the logic how to pick URL-s to test

production -> https://packrat.pages.dev
preview URLs  -> When we make changes in PRS the preview URL is generated and there are production + PR changes

So when we link PRS to test, you can use preview URLS, of that PR, otherwise you can use the production link

Feel free to reach me when you have any questions

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian, noted. Initially, I thought these were the live versions, not realizing they were from the PR links. Thanks for the clarification.

**Comment by taronaleksanian** [comment]
@EngrAJ8888 @jeweltee 
The issues were fixed on this PR, please check https://github.com/andrew-bierman/PackRat/pull/863

Let me show you how it works now

The issue you reported on units was fixed this way, now it relies on user preference, which he/she selected from the settings. The way you suggested is quite a good idea I guess we can implement it later (meaning select units for each pack).

Also global items now copied and changes made from internal item, don't affect on global items,

Thanks!

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian
Got it! I checked using the production link since the PR link has been merged into Andrew Testing. The units' issue is now working as expected. However, I noticed that editing a global item in the pack still affects the listed item in the global section. For instance, when I tried editing the weight to 5lbs, it changed the weight in the global items as well. Thank you!
