### ISSUE TITLE
Trip screen status tracking

### ISSUE THREAD

**Issue by taronaleksanian** [andrew-bierman/PackRat#852]
@jeweltee @EngrAJ8888 Hi,  I pushed a stable version for trips too, I think we can track the status of the screen here, Thanks
https://github.com/andrew-bierman/PackRat/pull/849

**Comment by jeweltee** [comment]
@taronaleksanian Hi. I just checked the update. The trip weather is now fixed. There are still several issues, the dropdown menu is not retracting automatically, and when clicking on the choices in the dropdown menu it's not responsive.  Also, the choices in the "Nearby Parks" are not clickable. 

here's a screen record for reference 
![82C00A1B-05DE-4657-9F4A-8E243162A443_1_102_a](https://github.com/andrew-bierman/PackRat/assets/166146993/1307ca0a-ff04-4756-9e6e-d21b67c5cc8b)

**Comment by taronaleksanian** [comment]
@jeweltee the issues was fixed, please check it out here
https://fix-trip-weather-not-fireing.packrat.pages.dev/

**Comment by jeweltee** [comment]
@taronaleksanian thanks for the update! the issues are fixed, but the response of the trip weather and map is a little slow upon choosing a destination.

**Comment by jeweltee** [comment]
@taronaleksanian thanks for the update! the said issues are fixed, but the response of the trip weather and map is a little slow upon choosing a destination. Also, I just noticed on other destinations the weather and map data are not showing up. here are screen records of 2 different destinations : 


https://github.com/andrew-bierman/PackRat/assets/166146993/4edfe143-32c8-4910-a6f3-5d07d74241c4


https://github.com/andrew-bierman/PackRat/assets/166146993/576ee79c-a310-4122-8ccd-94642f6ff454

**Comment by EngrAJ8888** [comment]
Hi @taronaleksanian , I've encountered the same issues that Jewel reported. Specifically, when I search for certain places, I'm getting empty maps. Thank you!

**Comment by taronaleksanian** [comment]
@EngrAJ8888 @jeweltee thanks, I'll fix it too

**Comment by jeweltee** [comment]
Hey @taronaleksanian adding this issue : when you navigate to the trips page and click on "view owner" it's showing Application error. Please refer to the screen record below. Thanks! 
[b35b4e40-b7a3-416f-b2a5-f0b68c24dd83.webm](https://github.com/andrew-bierman/PackRat/assets/166146993/a355fe9b-095f-478f-8029-104041ee5433)

**Comment by MuhammadHassan03** [comment]
is there any dev wokring on this issue?

> Hey @taronaleksanian adding this issue : when you navigate to the trips page and click on "view owner" it's showing Application error. Please refer to the screen record below. Thanks! [b35b4e40-b7a3-416f-b2a5-f0b68c24dd83.webm](https://github.com/andrew-bierman/PackRat/assets/166146993/a355fe9b-095f-478f-8029-104041ee5433)

**Comment by andrew-bierman** [comment]
> is there any dev wokring on this issue?
> 
> > Hey @taronaleksanian adding this issue : when you navigate to the trips page and click on "view owner" it's showing Application error. Please refer to the screen record below. Thanks! [b35b4e40-b7a3-416f-b2a5-f0b68c24dd83.webm](https://github.com/andrew-bierman/PackRat/assets/166146993/a355fe9b-095f-478f-8029-104041ee5433)

No it’s available, you can take it on
