### ISSUE TITLE
Reset Password Functionality Issue

### ISSUE THREAD

**Issue by jeweltee** [andrew-bierman/PackRat#865]
**Describe the bug**
The Reset Password functionality on the website is not functioning as expected

**To Reproduce**
1. Go to " https://packrat.pages.dev/ "
2. Navigate to the "Menu" and click "LogIn"
3. Click on " Reset Password? " 
4. Click on " Request Password Reset Email " 
5. Enter your email and click " Send Email "
6. There will be a pop-up message "Password reset email sent" 
7. Check your inbox 

**Expected behavior**
Upon submitting the password reset request, users should receive an email containing instructions and a link to reset their password

**Actual behavior**
After submitting the password reset request, users do not receive any email confirmation or instructions for resetting password.

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 
 - Browser Google Chrome
 - Version : 14.0

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro
 - OS: iOs 17.4
 - Browser Safari,Chrome
 - Version 17.4

**Comment by pinocchio-life-like** [comment]
@jeweltee You can Test it here: https://packrat.world/password-reset and close this issue

**Comment by jeweltee** [comment]
@pinocchio-life-like hi. I tested this and it shows this error... ![image](https://github.com/andrew-bierman/PackRat/assets/166146993/9ac6676d-3a9a-4984-b65c-9feeeb3a758c)

**Comment by jeweltee** [comment]
Issue fixed. Closing this ticket
