### ISSUE TITLE
Fixing Pack Addition Error and Adding Copy Feature

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#882]
**Describe the bug**
- [x]  Implement Copy Option where users can duplicate entire packs created by others, leading them to a new page where they can modify the cloned pack as desired.
- [x]  Users should be able to add items from global. Editing a cloned global item in the pack should not affect the listed item in the global section. 
- [x] Users can't add items when creating a pack. Clicking "Calculate Pack Score" makes all manually added items disappear. Please see video below for reference.
https://github.com/andrew-bierman/PackRat/assets/122357250/6cca0a80-d791-4bf3-b5e1-bdeea2bdffc0

**To Reproduce**
1. Visit the URL: https://packrat.pages.dev
2. Log in to your account with the following credentials:
   Email: [zoot3@email.com](mailto:zoot3@email.com)
   Password: 12345678
5. Click on the "Create a pack" option, under quick actions.
6. Begin adding items to your pack 
7. Select 'Calculate Score'

**Expected behavior**
1. Users should be able to edit global items they've cloned/added to their pack, and any changes from the global items should not affect the items on the user's pack.
2. Added items retains unless the user chooses to delete them.

**Comment by Isthisanmol** [comment]
Hi  @andrew-bierman, @EngrAJ8888 , I  am getting an error on adding item to pack: 
""error":{"message":"D1_ERROR: table item has no column named owner_id","code":-32603" I think this is related to database.
![Screenshot from 2024-05-03 19-11-04](https://github.com/andrew-bierman/PackRat/assets/106021226/893cb5c8-1245-4aab-ac85-73b08ad19f95)

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, I've checked the live version, and two items are already fixed. The only task left is to add the copy option. Thank you for working on this one! :)

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, I have checked the second issue on native. It was not working as expected so I fixed it on native. Please check PR: #900 and tell me if any issues or updates.Thanks.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol , thank you for making the updates!

I'd also like to add this item to the list of needed updates:
- [ ] Fix the pack creation view feature. Currently, after clicking 'Add Pack', users remain on the same page instead of being directed to the Pack Creation page as expected. Consequently, users are required to navigate to the 'Pack' menu to edit newly added packs.

![image](https://github.com/andrew-bierman/PackRat/assets/122357250/6b56da90-136a-4cf4-8a1d-0e120d7df639)
Please see photo above - it only stays on this page.

**Comment by jeweltee** [comment]
hi @Isthisanmol I want to add this also:

- [ ] The 'edit' option for items in the old packs created is missing, but it's available for the newly created packs. 
please see images below, Thanks! 
<img width="1433" alt="Screenshot 2024-05-07 at 21 10 26" src="https://github.com/andrew-bierman/PackRat/assets/166146993/dda6a825-b223-4992-82d3-44e83deb638f">
<img width="1415" alt="Screenshot 2024-05-07 at 21 10 03" src="https://github.com/andrew-bierman/PackRat/assets/166146993/f7d48e1d-bc00-498f-ba45-8d13c6d0743d">

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol , thank you for making the updates!
> 
> I'd also like to add this item to the list of needed updates:
> 
>     * [ ]  Fix the pack creation view feature. Currently, after clicking 'Add Pack', users remain on the same page instead of being directed to the Pack Creation page as expected. Consequently, users are required to navigate to the 'Pack' menu to edit newly added packs.
> 
> 
> ![image](https://private-user-images.githubusercontent.com/122357250/328447348-6b56da90-136a-4cf4-8a1d-0e120d7df639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTY1NDcsIm5iZiI6MTcxNTA5NjI0NywicGF0aCI6Ii8xMjIzNTcyNTAvMzI4NDQ3MzQ4LTZiNTZkYTkwLTEzNmEtNGNmNC04YTFkLTBlMTIwZDdkZjYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNTM3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjYyN2M5NWJlMTg2ZGY2ZDkxMjI0MTBhNDAwMTQ2Y2E3YjA2MjBkZGYzZTk5YmRkZDM1MmY4NWJhMzlmNmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1qGI6NE35AflJdiosDKtqHgYrXQO2rCpDwqSS_6syXI) Please see photo above - it only stays on this page.

Hi @EngrAJ8888, Please check PR: #906 for the above issue and tell me if any issues or updates.

**Comment by Isthisanmol** [comment]
> hi @Isthisanmol I want to add this also:
> 
>     * [ ]  The 'edit' option for items in the old packs created is missing, but it's available for the newly created packs.
>       please see images below, Thanks!
> 
> 
> <img alt="Screenshot 2024-05-07 at 21 10 26" width="1433" src="https://private-user-images.githubusercontent.com/166146993/328564955-dda6a825-b223-4992-82d3-44e83deb638f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTk2NTUsIm5iZiI6MTcxNTA5OTM1NSwicGF0aCI6Ii8xNjYxNDY5OTMvMzI4NTY0OTU1LWRkYTZhODI1LWIyMjMtNDk5Mi04MmQzLTQ0ZTgzZGViNjM4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNjI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZjMzZmE5ZTdjYzRkZGUwNzJhODhlZWFjNDc5ZWI2NWQxOWI3YjQ0ZWE5ZDc0YmFiY2Y0OTMzZWY4NzhjOGZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hRkYST1HUBpE3ybTz4i1l_YYz1jN-OudCDlwPGZfPvg"> <img alt="Screenshot 2024-05-07 at 21 10 03" width="1415" src="https://private-user-images.githubusercontent.com/166146993/328564986-f7d48e1d-bc00-498f-ba45-8d13c6d0743d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTk2NTUsIm5iZiI6MTcxNTA5OTM1NSwicGF0aCI6Ii8xNjYxNDY5OTMvMzI4NTY0OTg2LWY3ZDQ4ZTFkLWJjMDAtNDk4Zi1iYTQ1LThkMTNjNmQwNzQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNjI5MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZTI4ZGQyMGRiM2IwZTU1OWE4Y2QyYWRkMWYwZTUwNzM3ZmJhNWQ0YzBjNGEwMTIyNWQ0ZDY4NmI3NGNlMDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MowKvjuI3Z6G1FnzkNwrw651F1kD0e94iGrbXf1OW8A">

Hi @jeweltee, I've checked this. It's not a matter of a new pack v/s an old pack. The owner of the item has the exclusive ability to edit it. When I compare two different items from the same pack, I notice that one only offers the option to delete it, while the other provides both options. This is because I am the owner of the second item, not the first one. Hence, I see both options only for the second item. I'll attach screenshots of both items for reference.
![2](https://github.com/andrew-bierman/PackRat/assets/106021226/e6e27b21-742c-4408-ae2b-7149df1915c5)
![1](https://github.com/andrew-bierman/PackRat/assets/106021226/d10eb04f-9773-4842-8b5a-18d4a62ac3a2)

**Comment by Isthisanmol** [comment]
And also @jeweltee Please check PR: #907. The dropdown for edit and delete of items was not working on native. Therefore, I fixed it. Let me know if any issues or updates. Thanks.

**Comment by EngrAJ8888** [comment]
> > Hi @Isthisanmol , thank you for making the updates!
> > I'd also like to add this item to the list of needed updates:
> > ```
> > * [ ]  Fix the pack creation view feature. Currently, after clicking 'Add Pack', users remain on the same page instead of being directed to the Pack Creation page as expected. Consequently, users are required to navigate to the 'Pack' menu to edit newly added packs.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://private-user-images.githubusercontent.com/122357250/328447348-6b56da90-136a-4cf4-8a1d-0e120d7df639.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTY1NDcsIm5iZiI6MTcxNTA5NjI0NywicGF0aCI6Ii8xMjIzNTcyNTAvMzI4NDQ3MzQ4LTZiNTZkYTkwLTEzNmEtNGNmNC04YTFkLTBlMTIwZDdkZjYzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNTM3MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjYyN2M5NWJlMTg2ZGY2ZDkxMjI0MTBhNDAwMTQ2Y2E3YjA2MjBkZGYzZTk5YmRkZDM1MmY4NWJhMzlmNmVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1qGI6NE35AflJdiosDKtqHgYrXQO2rCpDwqSS_6syXI) Please see photo above - it only stays on this page.
> 
> Hi @EngrAJ8888, Please check PR: #906 for the above issue and tell me if any issues or updates.

Hi @Isthisanmol -  The PR has already been merged, and I noticed that the edit and delete options for items in the pack are no longer working. Could you please take a look into it as well? Thanks!

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, please check PR: #918 and let me know if any issues or updates.

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, please check PR:#926 for the edit and delete options for items in pack and let me know if any issues or updates.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, just wanted to let you know that I've added a comment on the PR. Thanks for making the updates!

**Comment by Isthisanmol** [comment]
> Hi @EngrAJ8888, please check PR: #918 and let me know if any issues or updates.

Any issues in this?

**Comment by Isthisanmol** [comment]
Hi @jeweltee @EngrAJ8888 , please check #937. Let me know if the issue persists.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol , I think there's some confusion about the update needed. The "Copy Pack" feature should be available when the owner browses packs created by other users, not on their own packs. The owner can clone packs from the Feed page and can modify the items in the cloned pack as well. Thanks!

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol , I think there's some confusion about the update needed. The "Copy Pack" feature should be available when the owner browses packs created by other users, not on their own packs. The owner can clone packs from the Feed page and can modify the items in the cloned pack as well. Thanks!

Should the other options on item and pack  also work like delete and save on pack and delete on item.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol , if you are referring to the cloned pack, yes that is correct. Users should have the ability to modify their cloned pack, with options to edit and delete.

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol , if you are referring to the cloned pack, yes that is correct. Users should have the ability to modify their cloned pack, with options to edit and delete.

Please Check #937 for the latest commits.

**Comment by EngrAJ8888** [comment]
Updates have been confirmed and validated. This task can now be marked as closed.
