### ISSUE TITLE
Trip Creation Functionalities 

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#883]
- [ ] The response of showing the Trip Weather, Map, Nearby Trails, and Nearby Parks is a little slow upon choosing a destination

- [ ] Weather and map data are not showing up on some destinations

**Comment by MuhammadHassan03** [comment]
I have started working on the second one issue

**Comment by jeweltee** [comment]
- [ ] Make the "Save" button more visible 
<img width="1440" alt="Screenshot 2024-05-04 at 12 36 56" src="https://github.com/andrew-bierman/PackRat/assets/166146993/55f046e8-f45a-4fcd-8d64-fe7159e9249c">

**Comment by jeweltee** [comment]
> I have started working on the second one issue

hi. Can you also include fixing the map from the destination query page, maps are empty on other destinations as well. Thanks!

**Comment by MuhammadHassan03** [comment]
> > I have started working on the second one issue
> 
> hi. Can you also include fixing the map from the destination query page, maps are empty on other destinations as well. Thanks!

Yeah, am working on it

**Comment by jeweltee** [comment]
- [ ] Arrows in the Create Trip page are not working. Please see the screen recording below for reference. Thank You! 

https://github.com/andrew-bierman/PackRat/assets/166146993/bda849d7-48de-46a4-b9b4-2f1d60c0b44a

**Comment by jeweltee** [comment]
- [ ] When you navigate to the trips page and click on "view owner" it shows an error. Please refer to the image below 
<img width="1436" alt="Screenshot 2024-05-08 at 23 02 34" src="https://github.com/andrew-bierman/PackRat/assets/166146993/a0ced7f0-e801-4d19-98e4-885a5873584b">

**Comment by andrew-bierman** [comment]
- [ ]  Full screen map is broken on web

**Comment by awais-codes** [comment]
> * [ ]   Full screen map is broken on web

I will be working on this one
