### ISSUE TITLE
Fix Text Formatting Issues

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#905]
**Describe the bug**
Following recent updates, several text elements require correction:

- [x]  Text appears narrow.
- [x]  Some text is underlined and needs to be removed.

**Screenshots**
These pages require text format updates:
![45](https://github.com/andrew-bierman/PackRat/assets/122357250/23b96726-14a9-4a39-bfbc-42a5e8407802)
![46](https://github.com/andrew-bierman/PackRat/assets/122357250/d045ecc9-bba8-4bde-9654-acbd257b792b)
![47](https://github.com/andrew-bierman/PackRat/assets/122357250/0d703eff-b241-4929-827d-88753676faac)
![48](https://github.com/andrew-bierman/PackRat/assets/122357250/32c3db37-5e11-47e3-9e2b-f84fe6d0bc9c)
![49](https://github.com/andrew-bierman/PackRat/assets/122357250/10daee16-f6e7-40e2-9a3f-eb13f5f4e55c)
![50](https://github.com/andrew-bierman/PackRat/assets/122357250/3b9f2911-5dc2-41c7-9292-7b00a7f8ba78)
![51](https://github.com/andrew-bierman/PackRat/assets/122357250/29b65a2f-54e0-49d1-a11e-47c74650c1d2)
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/444a93cb-76f4-4262-aeba-ed9b8b3e4bac)

**Desktop:**
Windows 11
Microsoft Edge
Version: 122.0.2365.92

**Comment by pinocchio-life-like** [comment]
https://github.com/andrew-bierman/PackRat/pull/931

Check it and lmk, Thank you

**Comment by EngrAJ8888** [comment]
Updates have been validated. This task is now closed.
