### ISSUE TITLE
Fix Page Layout Across All Pages

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#913]
**Describe the bug**
I noticed that the layout is inconsistent when using different screen monitors.

- [x] Let's update the page layout to maintain consistency by ensuring that all content doesn't just fill the width. Andrew suggested creating a reusable Layout component so we can maintain consistency across all screens.
- [x] Fix Nav Bar: It appears broken; please refer to the image below.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/19d30010-1cf9-411c-b964-9ba5a62136ab)
When scrolling down the page, it displays like this.

**Screenshots**
View on desktop:
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/ae8cd94a-694d-48b8-b275-cf8508785485)

laptop:
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/92df4077-e8b4-46b1-b552-d84ed60b67f4)

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, please check PR: #960 for the second item.

**Comment by EngrAJ8888** [comment]
Updates have been validated. This task is now closed.
