### ISSUE TITLE
Chat Feature Improvement

### ISSUE THREAD

**Issue by jeweltee** [andrew-bierman/PackRat#927]
**Describe the bug**
The text field does not automatically clear after the user sends a message. The previously sent message remains in the text field. 

**To Reproduce**
1. Go to 'https://packrat.pages.dev/'
2. Sign In to your account
   Email: zoot3@email.com
   Password: 12345678
3. Navigate to 'menu' and click 'feed'
4. Choose any of the created trips/packs
5. Scroll down and click 'Chat' 
6. Type a message and click 'send'

**Expected behavior**
After sending a message, the text box should clear automatically, providing a clean space for the user to type their next message without any remnants of the previous one.

**Screenshots**

https://github.com/andrew-bierman/PackRat/assets/166146993/ef9c03d9-f12f-4b73-8e16-95860250eb08

**Desktop (please complete the following information):**
- OS: macOS Sonoma
- Browser: Chrome
- Version 14.0

**Smartphone (please complete the following information):**
- Device: iPhone 13Pro
- OS: 17.4
- Browser: Chrome, Safari
- Version: 17.4

**Comment by pinocchio-life-like** [comment]
I have addressed this issue here: https://github.com/andrew-bierman/PackRat/pull/931

**Comment by jeweltee** [comment]
@pinocchio-life-like hi! I checked the update and it shows an error when I try to send a message. Please see the screen recording below, thanks! 


https://github.com/andrew-bierman/PackRat/assets/166146993/cc5b322d-c970-4eb4-97d8-3d0cced2c200
