### ISSUE TITLE
Android Mobile App : Bad UI 

### ISSUE THREAD

**Issue by jeweltee** [andrew-bierman/PackRat#941]
- [x] Fix overlapping texts/fields 

![441112468_811080560568571_6036286021286272445_n 2](https://github.com/andrew-bierman/PackRat/assets/166146993/0bb28a27-8eac-48cc-9ae0-8fca5a061eaf)
![441927221_1463129961260567_8143311013052975052_n 2](https://github.com/andrew-bierman/PackRat/assets/166146993/01a88b45-ac17-4c16-8481-05e2ecf943b1)

- [x] Resize the components in the Create Pack page 

![441169936_309422068924856_8371455467602300312_n 2](https://github.com/andrew-bierman/PackRat/assets/166146993/97ae7c6a-252d-4b64-abf5-355baca3a611)

- [x] Align and resize the texts 

![438293739_810569750556188_109656187286282769_n 2](https://github.com/andrew-bierman/PackRat/assets/166146993/afcd3440-c946-4b92-a1fb-f0d0411f757e)

**Comment by jeweltee** [comment]
- [ ] Resize Chat Component

![436226659_1936709563413336_6895942275736452952_n](https://github.com/andrew-bierman/PackRat/assets/166146993/ba25cb21-2259-45ef-b2e8-bbbe0995fbe4)

- [ ] Align 'View on GitHub' button to center (About Page)

![IMG_4987 2](https://github.com/andrew-bierman/PackRat/assets/166146993/d9e7873d-a4a9-4643-a7f7-046f76e99eef)

**Comment by jeweltee** [comment]
- [ ] Adjust the Trails and Nearby Parks select options so they stay within the form's boundaries

![441900994_1111943116707936_5092067095243568758_n](https://github.com/andrew-bierman/PackRat/assets/166146993/bd5e066b-9bff-430b-9f63-f4fdbe4d15d3)

**Comment by Isthisanmol** [comment]
Hi @jeweltee, please check PR:#958 for the first three items of the current issue and let me know if any updates or issues.

**Comment by Isthisanmol** [comment]
Hi @jeweltee, please check PR:#959 for the chat and about issue and let me know if any updates or issues.

**Comment by Isthisanmol** [comment]
> * [ ]  Adjust the Trails and Nearby Parks select options so they stay within the form's boundaries
> 
> 
> ![441900994_1111943116707936_5092067095243568758_n](https://private-user-images.githubusercontent.com/166146993/331439481-bd5e066b-9bff-430b-9f63-f4fdbe4d15d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTUxMjYsIm5iZiI6MTcxNjM1NDgyNiwicGF0aCI6Ii8xNjYxNDY5OTMvMzMxNDM5NDgxLWJkNWUwNjZiLTliZmYtNDMwYi05ZjYzLWY0ZmRiZTRkMTVkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNTEzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTk5YjFlYzA0NDZiZDNlZGRhYTA1ZDg0ODc1MjE4ZWMxNTQ2MWM0YzBlYzY1MmI2N2MxMmM3NDdjOGYxMDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C4o5RBU1FyBA8nAvJuj8TUCK9FFNmXZhzkU3a-kGFpg)

Is this still there after the new build? Because I am not able to see this on my end. I am attaching the screenshot that I see on my end.
![1](https://github.com/andrew-bierman/PackRat/assets/106021226/7e3c3c42-38b6-443f-8aba-f1cee8ed9552)

**Comment by jeweltee** [comment]
> > * [ ]   Adjust the Trails and Nearby Parks select options so they stay within the form's boundaries
> > 
> > ![441900994_1111943116707936_5092067095243568758_n](https://private-user-images.githubusercontent.com/166146993/331439481-bd5e066b-9bff-430b-9f63-f4fdbe4d15d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTUxMjYsIm5iZiI6MTcxNjM1NDgyNiwicGF0aCI6Ii8xNjYxNDY5OTMvMzMxNDM5NDgxLWJkNWUwNjZiLTliZmYtNDMwYi05ZjYzLWY0ZmRiZTRkMTVkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQwNTEzNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTk5YjFlYzA0NDZiZDNlZGRhYTA1ZDg0ODc1MjE4ZWMxNTQ2MWM0YzBlYzY1MmI2N2MxMmM3NDdjOGYxMDEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.C4o5RBU1FyBA8nAvJuj8TUCK9FFNmXZhzkU3a-kGFpg)
> 
> Is this still there after the new build? Because I am not able to see this on my end. I am attaching the screenshot that I see on my end. ![1](https://private-user-images.githubusercontent.com/106021226/332670278-7e3c3c42-38b6-443f-8aba-f1cee8ed9552.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNjYzMDIsIm5iZiI6MTcxNjM2NjAwMiwicGF0aCI6Ii8xMDYwMjEyMjYvMzMyNjcwMjc4LTdlM2MzYzQyLTM4YjYtNDQzZi04YWJhLWYxY2VlOGVkOTU1Mi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjJUMDgyMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDk3MWQ1ODEwYTY2NTUwYjgxNmQxMTk2MzliOTdkYmQ1NDA5ZjdiOWNmOTIwZjI1ZWI5ZmU1ZDc3MGVmYjk5NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.zB-6cLpwRZInRu5vLDoAzCHhzcNG-i1FoIsyyJ5QBj4)

yes this issue still persists in the new build

**Comment by Isthisanmol** [comment]
> * Adjust the Trails and Nearby Parks select



> * [ ]  Adjust the Trails and Nearby Parks select options so they stay within the form's boundaries
> 
> 
> ![441900994_1111943116707936_5092067095243568758_n](https://private-user-images.githubusercontent.com/166146993/331439481-bd5e066b-9bff-430b-9f63-f4fdbe4d15d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDk4NTEsIm5iZiI6MTcxNjgwOTU1MSwicGF0aCI6Ii8xNjYxNDY5OTMvMzMxNDM5NDgxLWJkNWUwNjZiLTliZmYtNDMwYi05ZjYzLWY0ZmRiZTRkMTVkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxMTMyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzY5ZGI1NjFmY2Q1ZjliYjY0ZjhiZjU3ZDdjNGMwYmY4NzAwNDhjOTU1Njk3ZjkxY2MyNDZlYjI3OWVhYTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xB__Saq4I7TVk9YKd8QueXr2Ds5x840cJIMN2_fBXZU)

Hi @jeweltee, PR: #968 fixes this. Please check. If app crashes on creating trip then check it after the PR: Changes in style of largecard and weathercard #966  is merged.

**Comment by jeweltee** [comment]
> > * Adjust the Trails and Nearby Parks select
> 
> > * [ ]   Adjust the Trails and Nearby Parks select options so they stay within the form's boundaries
> > 
> > ![441900994_1111943116707936_5092067095243568758_n](https://private-user-images.githubusercontent.com/166146993/331439481-bd5e066b-9bff-430b-9f63-f4fdbe4d15d3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDk4NTEsIm5iZiI6MTcxNjgwOTU1MSwicGF0aCI6Ii8xNjYxNDY5OTMvMzMxNDM5NDgxLWJkNWUwNjZiLTliZmYtNDMwYi05ZjYzLWY0ZmRiZTRkMTVkMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxMTMyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzY5ZGI1NjFmY2Q1ZjliYjY0ZjhiZjU3ZDdjNGMwYmY4NzAwNDhjOTU1Njk3ZjkxY2MyNDZlYjI3OWVhYTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xB__Saq4I7TVk9YKd8QueXr2Ds5x840cJIMN2_fBXZU)
> 
> Hi @jeweltee, PR: #968 fixes this. Please check. If app crashes on creating trip then check it after the PR: Changes in style of largecard and weathercard #966 is merged.

@Isthisanmol Thanks for this update. The issue is now fixed!
