### ISSUE TITLE
Android Mobile App: Screen Issues, App Crash, Blank Items Page

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#943]
**Describe the bug**

- [x] Welcome/sign-in page displays a white screen
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/af61f03c-3135-4110-9b1a-f669d132a673)

- [ ]  When viewing Trips, the screen only shows a white screen.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/a72e7865-2f8e-4a64-9c06-6b61e983d5c0)

- [ ]  The app crashes and forces a stop when trying to create a Trip.
- [ ]  The Items page is blank; no options to add or list items are available.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/f2d8bd0d-65bf-4492-8548-043d50359146)

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, I think the third item will be fixed once PR: Changes in style of largecard and weathercard #966  is merged.

**Comment by Isthisanmol** [comment]
> Hi @EngrAJ8888, I think the third item will be fixed once PR: Changes in style of largecard and weathercard #966 is merged. And please explain about first item.

**Comment by EngrAJ8888** [comment]
Hi @Isthisanmol, Got it! I'll review this once PR #966 is merged.
Regarding the first item, please refer to the photo below for context:
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/d32d546f-85ff-43dd-9400-d7c4a42cc110)

It's showing only a white screen, with only the screen below visible.
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/a2d13a1b-bfee-458e-881b-7c2ef566f9be)

Thanks!

**Comment by Isthisanmol** [comment]
> Hi @Isthisanmol, Got it! I'll review this once PR #966 is merged. Regarding the first item, please refer to the photo below for context: ![image](https://private-user-images.githubusercontent.com/122357250/334105006-d32d546f-85ff-43dd-9400-d7c4a42cc110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg0NDAsIm5iZiI6MTcxNzEzODE0MCwicGF0aCI6Ii8xMjIzNTcyNTAvMzM0MTA1MDA2LWQzMmQ1NDZmLTg1ZmYtNDNkZC05NDAwLWQ3YzRhNDJjYzExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWUxMmViOTM0MmM3M2M0YTExMGRmYWE4OTFhZmMzY2FlNWI0MGFmM2EwMmFkMDE0MzBkMjgzZmI5MzhmZjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OgIyeTT4DiNBAWMFHtHIEcleEU6GxE-Pc8BfTlzglgA)
> 
> It's showing only a white screen, with only the screen below visible. ![image](https://private-user-images.githubusercontent.com/122357250/334105261-a2d13a1b-bfee-458e-881b-7c2ef566f9be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg0NDAsIm5iZiI6MTcxNzEzODE0MCwicGF0aCI6Ii8xMjIzNTcyNTAvMzM0MTA1MjYxLWEyZDEzYTFiLWJmZWUtNDU4ZS04ODFiLTdjMmVmNTY2ZjliZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTI5YWEwYWZiNDcyOGZkZDM0ODA4MGY0Y2FmZTg4YzEyODM1YzY4YTFkMGEyZWY1NjkyMzk4OTMwYTQzZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7k3kGOWu3IwnpEGLzJ5dCrkfgXgbMyosc3-Mj3aQF7E)
> 
> Thanks!

Hi @EngrAJ8888, should we display only logo of the app at the landing page as it is a mobile app?

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888, please check PR: #974 for the first item and let me know if we have to make any changes.

**Comment by EngrAJ8888** [comment]
> > Hi @Isthisanmol, Got it! I'll review this once PR #966 is merged. Regarding the first item, please refer to the photo below for context: ![image](https://private-user-images.githubusercontent.com/122357250/334105006-d32d546f-85ff-43dd-9400-d7c4a42cc110.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg0NDAsIm5iZiI6MTcxNzEzODE0MCwicGF0aCI6Ii8xMjIzNTcyNTAvMzM0MTA1MDA2LWQzMmQ1NDZmLTg1ZmYtNDNkZC05NDAwLWQ3YzRhNDJjYzExMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWUxMmViOTM0MmM3M2M0YTExMGRmYWE4OTFhZmMzY2FlNWI0MGFmM2EwMmFkMDE0MzBkMjgzZmI5MzhmZjIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OgIyeTT4DiNBAWMFHtHIEcleEU6GxE-Pc8BfTlzglgA)
> > It's showing only a white screen, with only the screen below visible. ![image](https://private-user-images.githubusercontent.com/122357250/334105261-a2d13a1b-bfee-458e-881b-7c2ef566f9be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzg0NDAsIm5iZiI6MTcxNzEzODE0MCwicGF0aCI6Ii8xMjIzNTcyNTAvMzM0MTA1MjYxLWEyZDEzYTFiLWJmZWUtNDU4ZS04ODFiLTdjMmVmNTY2ZjliZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQwNjQ5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NTI5YWEwYWZiNDcyOGZkZDM0ODA4MGY0Y2FmZTg4YzEyODM1YzY4YTFkMGEyZWY1NjkyMzk4OTMwYTQzZDE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7k3kGOWu3IwnpEGLzJ5dCrkfgXgbMyosc3-Mj3aQF7E)
> > Thanks!
> 
> Hi @EngrAJ8888, should we display only logo of the app at the landing page as it is a mobile app?


Hi @Isthisanmol, Apologies for the delayed response. Yes, that would be great. I've reviewed the PR, this looks great!
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/b3461946-668a-4db5-9e58-0ac1746f74b6)

However, we're still experiencing the white screen issue. Ideally, the welcome page/Homepage should mirror the website
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/412c4475-87b3-4d1c-a220-76484373e637)

Currently, when the app is launched, it only displays the login/signup page:
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/1aa60d72-3365-4a61-9b90-f2a445628df3)

Let me know if you need further clarification. Thank you!

**Comment by Isthisanmol** [comment]
Hi, @EngrAJ8888 please check PR: #976 for fourth item.
