### ISSUE TITLE
Enhancement of Login/Register Screen

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#950]
Describe the bug
Integrating Tamagui Bento UI and Enhancing Login/Register Screen:

The current sign-in and register component requires enhancements to improve user experience and functionality.

-Modernize the UI with a clean, intuitive design. 
-Add social media sign-in options (ex. Facebook, Apple)
-Use high-contrast text and scalable fonts for better visibility 

**Screenshots**

![1c0ebdd7-c29c-4de9-a0c7-e8f0ed656971](https://github.com/andrew-bierman/PackRat/assets/166146993/891e8ef6-95f4-488d-9928-cb08bad0090d)
<img width="1437" alt="Screenshot 2024-05-18 at 16 31 21" src="https://github.com/andrew-bierman/PackRat/assets/166146993/5bfb6ecc-0eb7-493a-992c-3345e53a1fb7">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: chrome, safari
 - Version: 14.0

**Smartphone (please complete the following information):**
 - Device: iPhone 13Pro
 - OS: 17.4
 - Browser: Chrome, safari

**Comment by andrew-bierman** [comment]
@MuhammadHassan03 What is status on this one ?

**Comment by MuhammadHassan03** [comment]
> @MuhammadHassan03 What is status on this one ? 

@andrew-bierman it's already done here it is in this PR #967
