### ISSUE TITLE
Enhance Items Table Page: Integrate Pagination and Improve Text Visibility

### ISSUE THREAD

**Issue by EngrAJ8888** [andrew-bierman/PackRat#953]
**Describe the bug**
The Items table page requires an update, incorporating the Tamagui Bento UI. Please refer to the following list for the necessary improvements:

- [ ]  Implement pagination and sorting features in the Items table. Sort functionality should be based on Category.
- [ ]  Improve text visibility to ensure better legibility and enhance the overall user experience.

**Screenshots**
![image](https://github.com/andrew-bierman/PackRat/assets/122357250/2f2d4b7f-3bad-444f-898d-727f0e82546e)

**Desktop (please complete the following information):**
Windows 10 pro
Microsoft Edge
Version: 122.0.2365.92

**Smartphone (please complete the following information):**
Device: iPhone15
OS: iOs17.4
Browser: safari
Version: 17.4

**Additional context**
Utilize/Implement the new Tamagui Bento components for this update.

**Comment by awais-codes** [comment]
@jeweltee @EngrAJ8888 I would like to work on this one.

**Comment by jeweltee** [comment]
@awais-codes sure! No one has been assigned to this ticket yet.

**Comment by EngrAJ8888** [comment]
Hi @awais-codes , I hope you're doing well! Just wanted to check in and see if there's any update on this. It's our top priority to get it completed. Thank you!

**Comment by awais-codes** [comment]
> Hi @awais-codes , I hope you're doing well! Just wanted to check in and see if there's any update on this. It's our top priority to get it completed. Thank you! 

Apologies for reaching out late. I will deliver the work by tomorrow.

**Comment by awais-codes** [comment]
@EngrAJ8888  you can assign it to someone else. React native and expo are not my strong suite. I worked on web and I tried my best to find time to learn and work on this task. 

I am really sorry for causing such delay.

**Comment by Isthisanmol** [comment]
Hi @EngrAJ8888 , please review PR:#978. I think it closes this issue.
