### ISSUE TITLE
Native App Issues (High Priority)

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#997]
- [x] App is crashing when:
- creating and viewing trips

- opening and creating a pack

- [x] Created Packs and Trips are missing on the Packs, Trips and Feed Screen

![45521C28-C915-47C8-A120-A102F083C147](https://github.com/andrew-bierman/PackRat/assets/166146993/f45e1253-a2e0-4353-b6e6-e49f5213b283)

**Comment by EngrAJ8888** [comment]
I'd also like to add that:

- [ ] App crashes when viewing downloaded Maps

**Comment by shahzaib-manzoor** [comment]
Working On Second one ...

**Comment by Tadjaur** [comment]
> I'd also like to add that:
> 
> * [ ]  App crashes when viewing downloaded Maps

@EngrAJ8888  Please can you give me more context about this so I can follow the same step to have that bug on my side?

**Comment by EngrAJ8888** [comment]
Hi @Tadjaur - Sure! I've encountered this issue with the download maps feature. In the native app, there's a "Download Maps" functionality that isn't available on the web version. I saved a map, but when I try to view it, the app crashes. Please see video below for reference. Thanks! 

https://github.com/andrew-bierman/PackRat/assets/122357250/4c67cf0a-b740-46cb-b7ca-54f8c4b2fc5b

**Comment by Tadjaur** [comment]
Thanks, I'm working on it.

**Comment by Tadjaur** [comment]
> I'd also like to add that:
> 
> * [ ]  App crashes when viewing downloaded Maps

@EngrAJ8888 it is fixed in #1032
