### ISSUE TITLE
Android App Fixes: UI and Functionalities

### ISSUE THREAD

**Issue by JewelTee** [andrew-bierman/PackRat#999]
- [x] Align the search field to center 

![videoframe_10124](https://github.com/andrew-bierman/PackRat/assets/166146993/921d004b-971c-44da-908c-25dcc1a9aa86)

- [x] Align the text 'Download Maps' to center

![Screenshot_20240612_184805](https://github.com/andrew-bierman/PackRat/assets/166146993/f56f6937-38d5-4973-a0b2-06b1736b71b6)

- [x] When a user selects a sorting option from the dropdown menu, the chosen sorting method is not displayed. It remains to show "Sort By" 

https://github.com/andrew-bierman/PackRat/assets/166146993/1b458c4b-f4ee-4bc3-bbc7-9ffaaa4deafa

- [ ] App crashes when clicking on 'Download Map'

**Comment by Isthisanmol** [comment]
@JewelTee Please check -Sort name and alignment changes #1000 for first three items.

**Comment by Isthisanmol** [comment]
@JewelTee Please check - Replace RButton.Group to RStack #1003  for the last one.

**Comment by JewelTee** [comment]
Adding this one too: 

- [ ] When creating a pack, clicking on the "is public" option should not occupy the entire screen. Instead, make it a floating screen similar to editing an item option in the pack. The same applies to updating units in items and the Pack edit option.

![334112099-4f86e615-cc3d-4dcb-ac83-ff18fd802d60](https://github.com/andrew-bierman/PackRat/assets/166146993/2b2686a8-2a8a-4ebc-a1f1-dac29c26d800)

![334113115-b2424863-10c8-4c39-8b1b-f1d0bcbfccc6](https://github.com/andrew-bierman/PackRat/assets/166146993/5c132341-b5c9-4ab9-bbe2-b8f76d37bf2e)


![334111538-ea7d025c-0781-4c9e-bc10-1eb87cd1cdf0](https://github.com/andrew-bierman/PackRat/assets/166146993/9bf43229-bd7b-44f6-a5f6-fc3b261b67bd)

**Comment by Isthisanmol** [comment]
Hi, @JewelTee please check  #1010 for last one. It will be seen when you longpress the button.

**Comment by Isthisanmol** [comment]
@JewelTee Please check #1010 again for the remaining ones. These also works when you longpress the button.
